// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for NATGatewayPublicIPAssociationAPIVersion.
const (
	NATGatewayPublicIPAssociationAPIVersionNetworkAzureMUpboundIoV1Beta1 NATGatewayPublicIPAssociationAPIVersion = "network.azure.m.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationAPIVersion enum.
func (e NATGatewayPublicIPAssociationAPIVersion) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationAPIVersionNetworkAzureMUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationKind.
const (
	NATGatewayPublicIPAssociationKindNATGatewayPublicIPAssociation NATGatewayPublicIPAssociationKind = "NATGatewayPublicIPAssociation"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationKind enum.
func (e NATGatewayPublicIPAssociationKind) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationKindNATGatewayPublicIPAssociation:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolution.
const (
	NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolutionOptional NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolution = "Optional"
	NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolutionRequired NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolution enum.
func (e NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolution) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolutionOptional:
		return true
	case NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolve.
const (
	NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolveAlways       NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolve = "Always"
	NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolveIfNotPresent NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolve enum.
func (e NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolve) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolveAlways:
		return true
	case NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolution.
const (
	NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolutionOptional NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolution = "Optional"
	NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolutionRequired NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolution enum.
func (e NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolutionOptional:
		return true
	case NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolve.
const (
	NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolveAlways       NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolve = "Always"
	NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolveIfNotPresent NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolve enum.
func (e NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolveAlways:
		return true
	case NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolution.
const (
	NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolutionOptional NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolution = "Optional"
	NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolutionRequired NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolution enum.
func (e NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolution) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolutionOptional:
		return true
	case NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolve.
const (
	NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolveAlways       NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolve = "Always"
	NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolveIfNotPresent NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolve enum.
func (e NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolve) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolveAlways:
		return true
	case NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolution.
const (
	NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolutionOptional NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolution = "Optional"
	NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolutionRequired NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolution enum.
func (e NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolutionOptional:
		return true
	case NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolve.
const (
	NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolveAlways       NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolve = "Always"
	NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolveIfNotPresent NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolve enum.
func (e NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolveAlways:
		return true
	case NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolution.
const (
	NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolutionOptional NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolution = "Optional"
	NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolutionRequired NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolution enum.
func (e NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolution) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolutionOptional:
		return true
	case NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolve.
const (
	NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolveAlways       NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolve = "Always"
	NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolveIfNotPresent NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolve enum.
func (e NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolve) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolveAlways:
		return true
	case NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolution.
const (
	NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolutionOptional NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolution = "Optional"
	NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolutionRequired NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolution enum.
func (e NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolutionOptional:
		return true
	case NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolve.
const (
	NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolveAlways       NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolve = "Always"
	NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolveIfNotPresent NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolve enum.
func (e NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolveAlways:
		return true
	case NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolution.
const (
	NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolutionOptional NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolution = "Optional"
	NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolutionRequired NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolution enum.
func (e NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolution) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolutionOptional:
		return true
	case NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolve.
const (
	NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolveAlways       NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolve = "Always"
	NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolveIfNotPresent NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolve enum.
func (e NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolve) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolveAlways:
		return true
	case NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolution.
const (
	NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolutionOptional NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolution = "Optional"
	NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolutionRequired NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolution enum.
func (e NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolutionOptional:
		return true
	case NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolve.
const (
	NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolveAlways       NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolve = "Always"
	NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolveIfNotPresent NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolve enum.
func (e NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolveAlways:
		return true
	case NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for NATGatewayPublicIPAssociationSpecManagementPoliciesItem.
const (
	NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItem               NATGatewayPublicIPAssociationSpecManagementPoliciesItem = "*"
	NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemCreate         NATGatewayPublicIPAssociationSpecManagementPoliciesItem = "Create"
	NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemDelete         NATGatewayPublicIPAssociationSpecManagementPoliciesItem = "Delete"
	NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemLateInitialize NATGatewayPublicIPAssociationSpecManagementPoliciesItem = "LateInitialize"
	NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemObserve        NATGatewayPublicIPAssociationSpecManagementPoliciesItem = "Observe"
	NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemUpdate         NATGatewayPublicIPAssociationSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the NATGatewayPublicIPAssociationSpecManagementPoliciesItem enum.
func (e NATGatewayPublicIPAssociationSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItem:
		return true
	case NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemCreate:
		return true
	case NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemDelete:
		return true
	case NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemLateInitialize:
		return true
	case NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemObserve:
		return true
	case NATGatewayPublicIPAssociationSpecManagementPoliciesItemNATGatewayPublicIPAssociationSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoUpboundMAzureNetworkV1Beta1NATGatewayPublicIPAssociation NATGatewayPublicIPAssociation is the Schema for the NATGatewayPublicIPAssociations API. Manages the association between a NAT Gateway and a Public IP.
type IoUpboundMAzureNetworkV1Beta1NATGatewayPublicIPAssociation = NATGatewayPublicIPAssociation

// NATGatewayPublicIPAssociationAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type NATGatewayPublicIPAssociationAPIVersion string

// NATGatewayPublicIPAssociationKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type NATGatewayPublicIPAssociationKind string

// NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolution string

// NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolve string

// NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicy Policies for referencing.
type NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicyResolve `json:"resolve,omitempty"`
}

// NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRef Reference to a NATGateway in network to populate natGatewayId.
type NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRefPolicy `json:"policy,omitempty"`
}

// NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolution string

// NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolve string

// NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicy Policies for selection.
type NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelector Selector for a NATGateway in network to populate natGatewayId.
type NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelectorPolicy `json:"policy,omitempty"`
}

// NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolution string

// NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolve string

// NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicy Policies for referencing.
type NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicyResolve `json:"resolve,omitempty"`
}

// NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRef Reference to a PublicIP in network to populate publicIpAddressId.
type NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRefPolicy `json:"policy,omitempty"`
}

// NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolution string

// NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolve string

// NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicy Policies for selection.
type NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelector Selector for a PublicIP in network to populate publicIpAddressId.
type NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelectorPolicy `json:"policy,omitempty"`
}

// NATGatewayPublicIPAssociationSpecForProvider defines model for io.upbound.m.azure.network.v1beta1.NATGatewayPublicIPAssociation.spec.forProvider.
type NATGatewayPublicIPAssociationSpecForProvider struct {
	// NatGatewayID The ID of the NAT Gateway. Changing this forces a new resource to be created.
	NatGatewayID *string `json:"natGatewayId,omitempty"`

	// NatGatewayIDRef Reference to a NATGateway in network to populate natGatewayId.
	NatGatewayIDRef *NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDRef `json:"natGatewayIdRef,omitempty"`

	// NatGatewayIDSelector Selector for a NATGateway in network to populate natGatewayId.
	NatGatewayIDSelector *NATGatewayPublicIPAssociationSpecForProviderNatGatewayIDSelector `json:"natGatewayIdSelector,omitempty"`

	// PublicIPAddressID The ID of the Public IP which this NAT Gateway which should be connected to. Changing this forces a new resource to be created.
	PublicIPAddressID *string `json:"publicIpAddressId,omitempty"`

	// PublicIPAddressIDRef Reference to a PublicIP in network to populate publicIpAddressId.
	PublicIPAddressIDRef *NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDRef `json:"publicIpAddressIdRef,omitempty"`

	// PublicIPAddressIDSelector Selector for a PublicIP in network to populate publicIpAddressId.
	PublicIPAddressIDSelector *NATGatewayPublicIPAssociationSpecForProviderPublicIPAddressIDSelector `json:"publicIpAddressIdSelector,omitempty"`
}

// NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolution string

// NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolve string

// NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicy Policies for referencing.
type NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicyResolve `json:"resolve,omitempty"`
}

// NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRef Reference to a NATGateway in network to populate natGatewayId.
type NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRefPolicy `json:"policy,omitempty"`
}

// NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolution string

// NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolve string

// NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicy Policies for selection.
type NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelector Selector for a NATGateway in network to populate natGatewayId.
type NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelectorPolicy `json:"policy,omitempty"`
}

// NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolution string

// NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolve string

// NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicy Policies for referencing.
type NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicyResolve `json:"resolve,omitempty"`
}

// NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRef Reference to a PublicIP in network to populate publicIpAddressId.
type NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRefPolicy `json:"policy,omitempty"`
}

// NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolution string

// NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolve string

// NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicy Policies for selection.
type NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelector Selector for a PublicIP in network to populate publicIpAddressId.
type NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelectorPolicy `json:"policy,omitempty"`
}

// NATGatewayPublicIPAssociationSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type NATGatewayPublicIPAssociationSpecInitProvider struct {
	// NatGatewayID The ID of the NAT Gateway. Changing this forces a new resource to be created.
	NatGatewayID *string `json:"natGatewayId,omitempty"`

	// NatGatewayIDRef Reference to a NATGateway in network to populate natGatewayId.
	NatGatewayIDRef *NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDRef `json:"natGatewayIdRef,omitempty"`

	// NatGatewayIDSelector Selector for a NATGateway in network to populate natGatewayId.
	NatGatewayIDSelector *NATGatewayPublicIPAssociationSpecInitProviderNatGatewayIDSelector `json:"natGatewayIdSelector,omitempty"`

	// PublicIPAddressID The ID of the Public IP which this NAT Gateway which should be connected to. Changing this forces a new resource to be created.
	PublicIPAddressID *string `json:"publicIpAddressId,omitempty"`

	// PublicIPAddressIDRef Reference to a PublicIP in network to populate publicIpAddressId.
	PublicIPAddressIDRef *NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDRef `json:"publicIpAddressIdRef,omitempty"`

	// PublicIPAddressIDSelector Selector for a PublicIP in network to populate publicIpAddressId.
	PublicIPAddressIDSelector *NATGatewayPublicIPAssociationSpecInitProviderPublicIPAddressIDSelector `json:"publicIpAddressIdSelector,omitempty"`
}

// NATGatewayPublicIPAssociationSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type NATGatewayPublicIPAssociationSpecManagementPoliciesItem string

// NATGatewayPublicIPAssociationSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type NATGatewayPublicIPAssociationSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// NATGatewayPublicIPAssociationSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type NATGatewayPublicIPAssociationSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// NATGatewayPublicIPAssociationSpec NATGatewayPublicIPAssociationSpec defines the desired state of NATGatewayPublicIPAssociation
type NATGatewayPublicIPAssociationSpec struct {
	ForProvider *NATGatewayPublicIPAssociationSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *NATGatewayPublicIPAssociationSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]NATGatewayPublicIPAssociationSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *NATGatewayPublicIPAssociationSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *NATGatewayPublicIPAssociationSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// NATGatewayPublicIPAssociationStatusAtProvider defines model for io.upbound.m.azure.network.v1beta1.NATGatewayPublicIPAssociation.status.atProvider.
type NATGatewayPublicIPAssociationStatusAtProvider struct {
	ID *string `json:"id,omitempty"`

	// NatGatewayID The ID of the NAT Gateway. Changing this forces a new resource to be created.
	NatGatewayID *string `json:"natGatewayId,omitempty"`

	// PublicIPAddressID The ID of the Public IP which this NAT Gateway which should be connected to. Changing this forces a new resource to be created.
	PublicIPAddressID *string `json:"publicIpAddressId,omitempty"`
}

// NATGatewayPublicIPAssociationStatusConditionsItem A Condition that may apply to a resource.
type NATGatewayPublicIPAssociationStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// NATGatewayPublicIPAssociationStatus NATGatewayPublicIPAssociationStatus defines the observed state of NATGatewayPublicIPAssociation.
type NATGatewayPublicIPAssociationStatus struct {
	AtProvider *NATGatewayPublicIPAssociationStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]NATGatewayPublicIPAssociationStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// NATGatewayPublicIPAssociation NATGatewayPublicIPAssociation is the Schema for the NATGatewayPublicIPAssociations API. Manages the association between a NAT Gateway and a Public IP.
type NATGatewayPublicIPAssociation struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *NATGatewayPublicIPAssociationAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *NATGatewayPublicIPAssociationKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec NATGatewayPublicIPAssociationSpec defines the desired state of NATGatewayPublicIPAssociation
	Spec *NATGatewayPublicIPAssociationSpec `json:"spec,omitempty"`

	// Status NATGatewayPublicIPAssociationStatus defines the observed state of NATGatewayPublicIPAssociation.
	Status *NATGatewayPublicIPAssociationStatus `json:"status,omitempty"`
}

// IoUpboundMAzureNetworkV1Beta1NATGatewayPublicIPAssociationList NATGatewayPublicIPAssociationList is a list of NATGatewayPublicIPAssociation
type IoUpboundMAzureNetworkV1Beta1NATGatewayPublicIPAssociationList = NATGatewayPublicIPAssociationList

// NATGatewayPublicIPAssociationList NATGatewayPublicIPAssociationList is a list of NATGatewayPublicIPAssociation
type NATGatewayPublicIPAssociationList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of natgatewaypublicipassociations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundMAzureNetworkV1Beta1NATGatewayPublicIPAssociation `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
