// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for VirtualHubSecurityPartnerProviderAPIVersion.
const (
	VirtualHubSecurityPartnerProviderAPIVersionNetworkAzureMUpboundIoV1Beta1 VirtualHubSecurityPartnerProviderAPIVersion = "network.azure.m.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderAPIVersion enum.
func (e VirtualHubSecurityPartnerProviderAPIVersion) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderAPIVersionNetworkAzureMUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderKind.
const (
	VirtualHubSecurityPartnerProviderKindVirtualHubSecurityPartnerProvider VirtualHubSecurityPartnerProviderKind = "VirtualHubSecurityPartnerProvider"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderKind enum.
func (e VirtualHubSecurityPartnerProviderKind) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderKindVirtualHubSecurityPartnerProvider:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolution.
const (
	VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolutionOptional VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolution = "Optional"
	VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolutionRequired VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolution enum.
func (e VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolution) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolutionOptional:
		return true
	case VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolve.
const (
	VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolveAlways       VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolve = "Always"
	VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolveIfNotPresent VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolve enum.
func (e VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolve) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolveAlways:
		return true
	case VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolution.
const (
	VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolutionOptional VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolution = "Optional"
	VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolutionRequired VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolution enum.
func (e VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolution) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolutionOptional:
		return true
	case VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolve.
const (
	VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolveAlways       VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolve = "Always"
	VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolveIfNotPresent VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolve enum.
func (e VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolve) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolveAlways:
		return true
	case VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolution.
const (
	VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolutionOptional VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolution = "Optional"
	VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolutionRequired VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolution enum.
func (e VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolution) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolutionOptional:
		return true
	case VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolve.
const (
	VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolveAlways       VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolve = "Always"
	VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolveIfNotPresent VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolve enum.
func (e VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolve) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolveAlways:
		return true
	case VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolution.
const (
	VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolutionOptional VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolution = "Optional"
	VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolutionRequired VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolution enum.
func (e VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolutionOptional:
		return true
	case VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolve.
const (
	VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolveAlways       VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolve = "Always"
	VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolveIfNotPresent VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolve enum.
func (e VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolveAlways:
		return true
	case VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolution.
const (
	VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolutionOptional VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolution = "Optional"
	VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolutionRequired VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolution enum.
func (e VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolution) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolutionOptional:
		return true
	case VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolve.
const (
	VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolveAlways       VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolve = "Always"
	VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolveIfNotPresent VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolve enum.
func (e VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolve) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolveAlways:
		return true
	case VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolution.
const (
	VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolutionOptional VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolution = "Optional"
	VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolutionRequired VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolution enum.
func (e VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolutionOptional:
		return true
	case VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolve.
const (
	VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolveAlways       VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolve = "Always"
	VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolveIfNotPresent VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolve enum.
func (e VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolveAlways:
		return true
	case VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem.
const (
	VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItem               VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem = "*"
	VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemCreate         VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem = "Create"
	VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemDelete         VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem = "Delete"
	VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemLateInitialize VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem = "LateInitialize"
	VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemObserve        VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem = "Observe"
	VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemUpdate         VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem enum.
func (e VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItem:
		return true
	case VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemCreate:
		return true
	case VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemDelete:
		return true
	case VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemLateInitialize:
		return true
	case VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemObserve:
		return true
	case VirtualHubSecurityPartnerProviderSpecManagementPoliciesItemVirtualHubSecurityPartnerProviderSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoUpboundMAzureNetworkV1Beta1VirtualHubSecurityPartnerProvider VirtualHubSecurityPartnerProvider is the Schema for the VirtualHubSecurityPartnerProviders API. Manages a Security Partner Provider which could be associated to virtual hub.
type IoUpboundMAzureNetworkV1Beta1VirtualHubSecurityPartnerProvider = VirtualHubSecurityPartnerProvider

// VirtualHubSecurityPartnerProviderAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type VirtualHubSecurityPartnerProviderAPIVersion string

// VirtualHubSecurityPartnerProviderKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type VirtualHubSecurityPartnerProviderKind string

// VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolution string

// VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolve string

// VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicy Policies for referencing.
type VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicyResolve `json:"resolve,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRef Reference to a ResourceGroup in azure to populate resourceGroupName.
type VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRefPolicy `json:"policy,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolution string

// VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolve string

// VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicy Policies for selection.
type VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelector Selector for a ResourceGroup in azure to populate resourceGroupName.
type VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelectorPolicy `json:"policy,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolution string

// VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolve string

// VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicy Policies for referencing.
type VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRef Reference to a VirtualHub in network to populate virtualHubId.
type VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRefPolicy `json:"policy,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolution string

// VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolve string

// VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicy Policies for selection.
type VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelector Selector for a VirtualHub in network to populate virtualHubId.
type VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelectorPolicy `json:"policy,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecForProvider defines model for io.upbound.m.azure.network.v1beta1.VirtualHubSecurityPartnerProvider.spec.forProvider.
type VirtualHubSecurityPartnerProviderSpecForProvider struct {
	// Location The Azure Region where the Security Partner Provider should exist. Changing this forces a new resource to be created.
	Location *string `json:"location,omitempty"`

	// ResourceGroupName The name of the Resource Group where the Security Partner Provider should exist. Changing this forces a new resource to be created.
	ResourceGroupName *string `json:"resourceGroupName,omitempty"`

	// ResourceGroupNameRef Reference to a ResourceGroup in azure to populate resourceGroupName.
	ResourceGroupNameRef *VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameRef `json:"resourceGroupNameRef,omitempty"`

	// ResourceGroupNameSelector Selector for a ResourceGroup in azure to populate resourceGroupName.
	ResourceGroupNameSelector *VirtualHubSecurityPartnerProviderSpecForProviderResourceGroupNameSelector `json:"resourceGroupNameSelector,omitempty"`

	// SecurityProviderName The security provider name. Possible values are ZScaler, IBoss and Checkpoint is allowed. Changing this forces a new resource to be created.
	SecurityProviderName *string `json:"securityProviderName,omitempty"`

	// Tags A mapping of tags which should be assigned to the Security Partner Provider.
	Tags *map[string]string `json:"tags,omitempty"`

	// VirtualHubID The ID of the Virtual Hub within which this Security Partner Provider should be created. Changing this forces a new resource to be created.
	VirtualHubID *string `json:"virtualHubId,omitempty"`

	// VirtualHubIDRef Reference to a VirtualHub in network to populate virtualHubId.
	VirtualHubIDRef *VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDRef `json:"virtualHubIdRef,omitempty"`

	// VirtualHubIDSelector Selector for a VirtualHub in network to populate virtualHubId.
	VirtualHubIDSelector *VirtualHubSecurityPartnerProviderSpecForProviderVirtualHubIDSelector `json:"virtualHubIdSelector,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolution string

// VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolve string

// VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicy Policies for referencing.
type VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRef Reference to a VirtualHub in network to populate virtualHubId.
type VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRefPolicy `json:"policy,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolution string

// VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolve string

// VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicy Policies for selection.
type VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelector Selector for a VirtualHub in network to populate virtualHubId.
type VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelectorPolicy `json:"policy,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type VirtualHubSecurityPartnerProviderSpecInitProvider struct {
	// Location The Azure Region where the Security Partner Provider should exist. Changing this forces a new resource to be created.
	Location *string `json:"location,omitempty"`

	// SecurityProviderName The security provider name. Possible values are ZScaler, IBoss and Checkpoint is allowed. Changing this forces a new resource to be created.
	SecurityProviderName *string `json:"securityProviderName,omitempty"`

	// Tags A mapping of tags which should be assigned to the Security Partner Provider.
	Tags *map[string]string `json:"tags,omitempty"`

	// VirtualHubID The ID of the Virtual Hub within which this Security Partner Provider should be created. Changing this forces a new resource to be created.
	VirtualHubID *string `json:"virtualHubId,omitempty"`

	// VirtualHubIDRef Reference to a VirtualHub in network to populate virtualHubId.
	VirtualHubIDRef *VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDRef `json:"virtualHubIdRef,omitempty"`

	// VirtualHubIDSelector Selector for a VirtualHub in network to populate virtualHubId.
	VirtualHubIDSelector *VirtualHubSecurityPartnerProviderSpecInitProviderVirtualHubIDSelector `json:"virtualHubIdSelector,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem string

// VirtualHubSecurityPartnerProviderSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type VirtualHubSecurityPartnerProviderSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type VirtualHubSecurityPartnerProviderSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// VirtualHubSecurityPartnerProviderSpec VirtualHubSecurityPartnerProviderSpec defines the desired state of VirtualHubSecurityPartnerProvider
type VirtualHubSecurityPartnerProviderSpec struct {
	ForProvider *VirtualHubSecurityPartnerProviderSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *VirtualHubSecurityPartnerProviderSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]VirtualHubSecurityPartnerProviderSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *VirtualHubSecurityPartnerProviderSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *VirtualHubSecurityPartnerProviderSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// VirtualHubSecurityPartnerProviderStatusAtProvider defines model for io.upbound.m.azure.network.v1beta1.VirtualHubSecurityPartnerProvider.status.atProvider.
type VirtualHubSecurityPartnerProviderStatusAtProvider struct {
	// ID The ID of the Security Partner Provider.
	ID *string `json:"id,omitempty"`

	// Location The Azure Region where the Security Partner Provider should exist. Changing this forces a new resource to be created.
	Location *string `json:"location,omitempty"`

	// ResourceGroupName The name of the Resource Group where the Security Partner Provider should exist. Changing this forces a new resource to be created.
	ResourceGroupName *string `json:"resourceGroupName,omitempty"`

	// SecurityProviderName The security provider name. Possible values are ZScaler, IBoss and Checkpoint is allowed. Changing this forces a new resource to be created.
	SecurityProviderName *string `json:"securityProviderName,omitempty"`

	// Tags A mapping of tags which should be assigned to the Security Partner Provider.
	Tags *map[string]string `json:"tags,omitempty"`

	// VirtualHubID The ID of the Virtual Hub within which this Security Partner Provider should be created. Changing this forces a new resource to be created.
	VirtualHubID *string `json:"virtualHubId,omitempty"`
}

// VirtualHubSecurityPartnerProviderStatusConditionsItem A Condition that may apply to a resource.
type VirtualHubSecurityPartnerProviderStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// VirtualHubSecurityPartnerProviderStatus VirtualHubSecurityPartnerProviderStatus defines the observed state of VirtualHubSecurityPartnerProvider.
type VirtualHubSecurityPartnerProviderStatus struct {
	AtProvider *VirtualHubSecurityPartnerProviderStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]VirtualHubSecurityPartnerProviderStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// VirtualHubSecurityPartnerProvider VirtualHubSecurityPartnerProvider is the Schema for the VirtualHubSecurityPartnerProviders API. Manages a Security Partner Provider which could be associated to virtual hub.
type VirtualHubSecurityPartnerProvider struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *VirtualHubSecurityPartnerProviderAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *VirtualHubSecurityPartnerProviderKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec VirtualHubSecurityPartnerProviderSpec defines the desired state of VirtualHubSecurityPartnerProvider
	Spec *VirtualHubSecurityPartnerProviderSpec `json:"spec,omitempty"`

	// Status VirtualHubSecurityPartnerProviderStatus defines the observed state of VirtualHubSecurityPartnerProvider.
	Status *VirtualHubSecurityPartnerProviderStatus `json:"status,omitempty"`
}

// IoUpboundMAzureNetworkV1Beta1VirtualHubSecurityPartnerProviderList VirtualHubSecurityPartnerProviderList is a list of VirtualHubSecurityPartnerProvider
type IoUpboundMAzureNetworkV1Beta1VirtualHubSecurityPartnerProviderList = VirtualHubSecurityPartnerProviderList

// VirtualHubSecurityPartnerProviderList VirtualHubSecurityPartnerProviderList is a list of VirtualHubSecurityPartnerProvider
type VirtualHubSecurityPartnerProviderList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of virtualhubsecuritypartnerproviders. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundMAzureNetworkV1Beta1VirtualHubSecurityPartnerProvider `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
