# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_civocluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class ApiKeySecretRef(BaseModel):
    key: constr(min_length=1, max_length=253) | None = 'api-key'
    name: constr(min_length=1, max_length=253) | None = 'civo-credentials'
    namespace: constr(min_length=1, max_length=63) | None = 'crossplane-system'


class Credentials(BaseModel):
    name: constr(min_length=1, max_length=253) | None = 'default'
    type: Literal['ProviderConfig', 'ClusterProviderConfig'] | None = (
        'ClusterProviderConfig'
    )


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Gpu(BaseModel):
    acceleratorType: constr(min_length=1, max_length=63)
    """
    GPU accelerator type (e.g. nvidia-l40s, nvidia-a100). Used to label GPU nodes; the actual GPU and count are determined by the size.
    """


class NodePool(BaseModel):
    gpu: Gpu | None = None
    """
    GPU configuration. Required when role is GPU.
    """
    maxNodeCount: conint(ge=1, le=1000) | None = None
    """
    Maximum number of nodes for autoscaling. When set the node pool autoscales between minNodeCount (or nodeCount) and this. Civo has no server-side autoscaler, so the Kubernetes cluster autoscaler is installed on the cluster to drive the pool's node count through the Civo API. Omit for fixed-size pools.
    """
    minNodeCount: conint(ge=1, le=1000) | None = None
    """
    Minimum number of nodes for autoscaling. Defaults to nodeCount when maxNodeCount is set. Requires maxNodeCount.
    """
    name: constr(min_length=1, max_length=40)
    """
    Unique name for this node pool. Used as the pool's label in the Civo cluster.
    """
    nodeCount: conint(ge=1, le=1000) | None = 1
    """
    Number of nodes. Fixed unless maxNodeCount enables autoscaling.
    """
    role: Literal['System', 'GPU']
    """
    Determines what workloads this pool runs. System pools host controllers, gateways, and infrastructure. GPU pools host inference workloads and are tainted to exclude non-GPU pods.
    """
    size: constr(min_length=1, max_length=63)
    """
    Civo instance size for the pool's nodes (e.g. an.g1.l40s.kube.x1, g4p.kube.small). This is the instance type used by other clouds; list sizes with civo kubernetes size.
    """


class Spec(BaseModel):
    apiKeySecretRef: ApiKeySecretRef | None = None
    """
    Reference to a Secret key holding a plain Civo API token. The Kubernetes cluster autoscaler installed for pools with maxNodeCount set scales node pools through the Civo API, and its token is copied to the workload cluster from this key. The provider's own credentials Secret holds JSON, so the plain token is a separate key; the getting started guide creates both keys in one Secret. Defaults to the api-key key of the civo-credentials Secret in the crossplane-system namespace.
    """
    cni: Literal['flannel', 'cilium'] | None = 'flannel'
    """
    CNI plugin for the cluster. Civo supports flannel (its default) and cilium. Set at creation time only.
    """
    credentials: Credentials | None = None
    """
    Civo ProviderConfig or ClusterProviderConfig used to authenticate to the Civo API. Defaults to the ClusterProviderConfig named default.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    kubernetesVersion: constr(min_length=1, max_length=32) | None = None
    """
    Civo Kubernetes (k3s) version. Civo requires an exact version string including the k3s build suffix (e.g. 1.34.1-k3s1); list current versions with civo kubernetes versions. Choose 1.34 or newer so Dynamic Resource Allocation (how GPUs bind to pods) is generally available. Defaults to Civo's current default version.
    """
    nodePools: list[NodePool] = Field(..., max_length=8, min_length=1)
    """
    Node pools for the cluster. At least one System pool is required for controllers and infrastructure workloads.
    """
    region: constr(min_length=1, max_length=32)
    """
    Civo region for the cluster (e.g. LON1, NYC1, FRA1). GPU sizes vary by region; list availability with civo region ls and civo kubernetes size.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    type: Literal['Kubeconfig'] = 'Kubeconfig'
    """
    The type of credential this secret contains. Kubeconfig contains a kubeconfig file with the cluster endpoint, CA certificate, and static client certificates.
    """


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    secrets: list[Secret] | None = None
    """
    Secrets produced by this cluster. Consumers use these to authenticate to the cluster. All secrets are in the same namespace as this CivoCluster.
    """


class CivoCluster(BaseModel):
    apiVersion: Literal['infrastructure.modelplane.ai/v1alpha1'] | None = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['CivoCluster'] | None = 'CivoCluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    CivoClusterSpec defines the desired state of CivoCluster.
    """
    status: Status | None = None
    """
    CivoClusterStatus defines the observed state of CivoCluster.
    """


class CivoClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[CivoCluster]
    """
    List of civoclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """