// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for GlobalNetworkEndpointGroupAPIVersion.
const (
	GlobalNetworkEndpointGroupAPIVersionComputeGcpMUpboundIoV1Beta1 GlobalNetworkEndpointGroupAPIVersion = "compute.gcp.m.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the GlobalNetworkEndpointGroupAPIVersion enum.
func (e GlobalNetworkEndpointGroupAPIVersion) Valid() bool {
	switch e {
	case GlobalNetworkEndpointGroupAPIVersionComputeGcpMUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for GlobalNetworkEndpointGroupKind.
const (
	GlobalNetworkEndpointGroupKindGlobalNetworkEndpointGroup GlobalNetworkEndpointGroupKind = "GlobalNetworkEndpointGroup"
)

// Valid indicates whether the value is a known member of the GlobalNetworkEndpointGroupKind enum.
func (e GlobalNetworkEndpointGroupKind) Valid() bool {
	switch e {
	case GlobalNetworkEndpointGroupKindGlobalNetworkEndpointGroup:
		return true
	default:
		return false
	}
}

// Defines values for GlobalNetworkEndpointGroupSpecManagementPoliciesItem.
const (
	GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItem               GlobalNetworkEndpointGroupSpecManagementPoliciesItem = "*"
	GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemCreate         GlobalNetworkEndpointGroupSpecManagementPoliciesItem = "Create"
	GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemDelete         GlobalNetworkEndpointGroupSpecManagementPoliciesItem = "Delete"
	GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemLateInitialize GlobalNetworkEndpointGroupSpecManagementPoliciesItem = "LateInitialize"
	GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemObserve        GlobalNetworkEndpointGroupSpecManagementPoliciesItem = "Observe"
	GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemUpdate         GlobalNetworkEndpointGroupSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the GlobalNetworkEndpointGroupSpecManagementPoliciesItem enum.
func (e GlobalNetworkEndpointGroupSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItem:
		return true
	case GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemCreate:
		return true
	case GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemDelete:
		return true
	case GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemLateInitialize:
		return true
	case GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemObserve:
		return true
	case GlobalNetworkEndpointGroupSpecManagementPoliciesItemGlobalNetworkEndpointGroupSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoUpboundMGcpComputeV1Beta1GlobalNetworkEndpointGroup GlobalNetworkEndpointGroup is the Schema for the GlobalNetworkEndpointGroups API. A global network endpoint group contains endpoints that reside outside of Google Cloud.
type IoUpboundMGcpComputeV1Beta1GlobalNetworkEndpointGroup = GlobalNetworkEndpointGroup

// GlobalNetworkEndpointGroupAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type GlobalNetworkEndpointGroupAPIVersion string

// GlobalNetworkEndpointGroupKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type GlobalNetworkEndpointGroupKind string

// GlobalNetworkEndpointGroupSpecForProvider defines model for io.upbound.m.gcp.compute.v1beta1.GlobalNetworkEndpointGroup.spec.forProvider.
type GlobalNetworkEndpointGroupSpecForProvider struct {
	// DefaultPort The default port used if the port number is not specified in the
	// network endpoint.
	DefaultPort *float32 `json:"defaultPort,omitempty"`

	// Description An optional description of this resource. Provide this property when
	// you create the resource.
	Description *string `json:"description,omitempty"`

	// NetworkEndpointType Type of network endpoints in this network endpoint group.
	// Possible values are: INTERNET_IP_PORT, INTERNET_FQDN_PORT.
	NetworkEndpointType *string `json:"networkEndpointType,omitempty"`

	// Project The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty"`
}

// GlobalNetworkEndpointGroupSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type GlobalNetworkEndpointGroupSpecInitProvider struct {
	// DefaultPort The default port used if the port number is not specified in the
	// network endpoint.
	DefaultPort *float32 `json:"defaultPort,omitempty"`

	// Description An optional description of this resource. Provide this property when
	// you create the resource.
	Description *string `json:"description,omitempty"`

	// NetworkEndpointType Type of network endpoints in this network endpoint group.
	// Possible values are: INTERNET_IP_PORT, INTERNET_FQDN_PORT.
	NetworkEndpointType *string `json:"networkEndpointType,omitempty"`

	// Project The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty"`
}

// GlobalNetworkEndpointGroupSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type GlobalNetworkEndpointGroupSpecManagementPoliciesItem string

// GlobalNetworkEndpointGroupSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type GlobalNetworkEndpointGroupSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// GlobalNetworkEndpointGroupSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type GlobalNetworkEndpointGroupSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// GlobalNetworkEndpointGroupSpec GlobalNetworkEndpointGroupSpec defines the desired state of GlobalNetworkEndpointGroup
type GlobalNetworkEndpointGroupSpec struct {
	ForProvider *GlobalNetworkEndpointGroupSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *GlobalNetworkEndpointGroupSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]GlobalNetworkEndpointGroupSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *GlobalNetworkEndpointGroupSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *GlobalNetworkEndpointGroupSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// GlobalNetworkEndpointGroupStatusAtProvider defines model for io.upbound.m.gcp.compute.v1beta1.GlobalNetworkEndpointGroup.status.atProvider.
type GlobalNetworkEndpointGroupStatusAtProvider struct {
	// DefaultPort The default port used if the port number is not specified in the
	// network endpoint.
	DefaultPort *float32 `json:"defaultPort,omitempty"`

	// Description An optional description of this resource. Provide this property when
	// you create the resource.
	Description *string `json:"description,omitempty"`

	// ID an identifier for the resource with format projects/{{project}}/global/networkEndpointGroups/{{name}}
	ID *string `json:"id,omitempty"`

	// NetworkEndpointType Type of network endpoints in this network endpoint group.
	// Possible values are: INTERNET_IP_PORT, INTERNET_FQDN_PORT.
	NetworkEndpointType *string `json:"networkEndpointType,omitempty"`

	// Project The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty"`

	// SelfLink The URI of the created resource.
	SelfLink *string `json:"selfLink,omitempty"`
}

// GlobalNetworkEndpointGroupStatusConditionsItem A Condition that may apply to a resource.
type GlobalNetworkEndpointGroupStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// GlobalNetworkEndpointGroupStatus GlobalNetworkEndpointGroupStatus defines the observed state of GlobalNetworkEndpointGroup.
type GlobalNetworkEndpointGroupStatus struct {
	AtProvider *GlobalNetworkEndpointGroupStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]GlobalNetworkEndpointGroupStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// GlobalNetworkEndpointGroup GlobalNetworkEndpointGroup is the Schema for the GlobalNetworkEndpointGroups API. A global network endpoint group contains endpoints that reside outside of Google Cloud.
type GlobalNetworkEndpointGroup struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *GlobalNetworkEndpointGroupAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *GlobalNetworkEndpointGroupKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec GlobalNetworkEndpointGroupSpec defines the desired state of GlobalNetworkEndpointGroup
	Spec *GlobalNetworkEndpointGroupSpec `json:"spec,omitempty"`

	// Status GlobalNetworkEndpointGroupStatus defines the observed state of GlobalNetworkEndpointGroup.
	Status *GlobalNetworkEndpointGroupStatus `json:"status,omitempty"`
}

// IoUpboundMGcpComputeV1Beta1GlobalNetworkEndpointGroupList GlobalNetworkEndpointGroupList is a list of GlobalNetworkEndpointGroup
type IoUpboundMGcpComputeV1Beta1GlobalNetworkEndpointGroupList = GlobalNetworkEndpointGroupList

// GlobalNetworkEndpointGroupList GlobalNetworkEndpointGroupList is a list of GlobalNetworkEndpointGroup
type GlobalNetworkEndpointGroupList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of globalnetworkendpointgroups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundMGcpComputeV1Beta1GlobalNetworkEndpointGroup `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
