// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ServiceLinkedRoleAPIVersion.
const (
	ServiceLinkedRoleAPIVersionIamAwsUpboundIoV1Beta1 ServiceLinkedRoleAPIVersion = "iam.aws.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the ServiceLinkedRoleAPIVersion enum.
func (e ServiceLinkedRoleAPIVersion) Valid() bool {
	switch e {
	case ServiceLinkedRoleAPIVersionIamAwsUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for ServiceLinkedRoleKind.
const (
	ServiceLinkedRoleKindServiceLinkedRole ServiceLinkedRoleKind = "ServiceLinkedRole"
)

// Valid indicates whether the value is a known member of the ServiceLinkedRoleKind enum.
func (e ServiceLinkedRoleKind) Valid() bool {
	switch e {
	case ServiceLinkedRoleKindServiceLinkedRole:
		return true
	default:
		return false
	}
}

// Defines values for ServiceLinkedRoleSpecDeletionPolicy.
const (
	ServiceLinkedRoleSpecDeletionPolicyDelete ServiceLinkedRoleSpecDeletionPolicy = "Delete"
	ServiceLinkedRoleSpecDeletionPolicyOrphan ServiceLinkedRoleSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the ServiceLinkedRoleSpecDeletionPolicy enum.
func (e ServiceLinkedRoleSpecDeletionPolicy) Valid() bool {
	switch e {
	case ServiceLinkedRoleSpecDeletionPolicyDelete:
		return true
	case ServiceLinkedRoleSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for ServiceLinkedRoleSpecManagementPoliciesItem.
const (
	ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItem               ServiceLinkedRoleSpecManagementPoliciesItem = "*"
	ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemCreate         ServiceLinkedRoleSpecManagementPoliciesItem = "Create"
	ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemDelete         ServiceLinkedRoleSpecManagementPoliciesItem = "Delete"
	ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemLateInitialize ServiceLinkedRoleSpecManagementPoliciesItem = "LateInitialize"
	ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemObserve        ServiceLinkedRoleSpecManagementPoliciesItem = "Observe"
	ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemUpdate         ServiceLinkedRoleSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the ServiceLinkedRoleSpecManagementPoliciesItem enum.
func (e ServiceLinkedRoleSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItem:
		return true
	case ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemCreate:
		return true
	case ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemDelete:
		return true
	case ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemLateInitialize:
		return true
	case ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemObserve:
		return true
	case ServiceLinkedRoleSpecManagementPoliciesItemServiceLinkedRoleSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for ServiceLinkedRoleSpecProviderConfigRefPolicyResolution.
const (
	ServiceLinkedRoleSpecProviderConfigRefPolicyResolutionOptional ServiceLinkedRoleSpecProviderConfigRefPolicyResolution = "Optional"
	ServiceLinkedRoleSpecProviderConfigRefPolicyResolutionRequired ServiceLinkedRoleSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the ServiceLinkedRoleSpecProviderConfigRefPolicyResolution enum.
func (e ServiceLinkedRoleSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case ServiceLinkedRoleSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case ServiceLinkedRoleSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for ServiceLinkedRoleSpecProviderConfigRefPolicyResolve.
const (
	ServiceLinkedRoleSpecProviderConfigRefPolicyResolveAlways       ServiceLinkedRoleSpecProviderConfigRefPolicyResolve = "Always"
	ServiceLinkedRoleSpecProviderConfigRefPolicyResolveIfNotPresent ServiceLinkedRoleSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the ServiceLinkedRoleSpecProviderConfigRefPolicyResolve enum.
func (e ServiceLinkedRoleSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case ServiceLinkedRoleSpecProviderConfigRefPolicyResolveAlways:
		return true
	case ServiceLinkedRoleSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoUpboundAwsIamV1Beta1ServiceLinkedRole ServiceLinkedRole is the Schema for the ServiceLinkedRoles API. Provides an IAM service-linked role.
type IoUpboundAwsIamV1Beta1ServiceLinkedRole = ServiceLinkedRole

// ServiceLinkedRoleAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ServiceLinkedRoleAPIVersion string

// ServiceLinkedRoleKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ServiceLinkedRoleKind string

// ServiceLinkedRoleSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type ServiceLinkedRoleSpecDeletionPolicy string

// ServiceLinkedRoleSpecForProvider defines model for io.upbound.aws.iam.v1beta1.ServiceLinkedRole.spec.forProvider.
type ServiceLinkedRoleSpecForProvider struct {
	// AwsServiceName The AWS service to which this role is attached. You use a string similar to a URL but without the http:// in front. For example: elasticbeanstalk.amazonaws.com. To find the full list of services that support service-linked roles, check the docs.
	AwsServiceName *string `json:"awsServiceName,omitempty"`

	// CustomSuffix Additional string appended to the role name. Not all AWS services support custom suffixes.
	CustomSuffix *string `json:"customSuffix,omitempty"`

	// Description The description of the role.
	Description *string `json:"description,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// ServiceLinkedRoleSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type ServiceLinkedRoleSpecInitProvider struct {
	// AwsServiceName The AWS service to which this role is attached. You use a string similar to a URL but without the http:// in front. For example: elasticbeanstalk.amazonaws.com. To find the full list of services that support service-linked roles, check the docs.
	AwsServiceName *string `json:"awsServiceName,omitempty"`

	// CustomSuffix Additional string appended to the role name. Not all AWS services support custom suffixes.
	CustomSuffix *string `json:"customSuffix,omitempty"`

	// Description The description of the role.
	Description *string `json:"description,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// ServiceLinkedRoleSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type ServiceLinkedRoleSpecManagementPoliciesItem string

// ServiceLinkedRoleSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type ServiceLinkedRoleSpecProviderConfigRefPolicyResolution string

// ServiceLinkedRoleSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type ServiceLinkedRoleSpecProviderConfigRefPolicyResolve string

// ServiceLinkedRoleSpecProviderConfigRefPolicy Policies for referencing.
type ServiceLinkedRoleSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *ServiceLinkedRoleSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *ServiceLinkedRoleSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// ServiceLinkedRoleSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type ServiceLinkedRoleSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *ServiceLinkedRoleSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// ServiceLinkedRoleSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type ServiceLinkedRoleSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// ServiceLinkedRoleSpec ServiceLinkedRoleSpec defines the desired state of ServiceLinkedRole
type ServiceLinkedRoleSpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *ServiceLinkedRoleSpecDeletionPolicy `json:"deletionPolicy,omitempty"`
	ForProvider    *ServiceLinkedRoleSpecForProvider    `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *ServiceLinkedRoleSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]ServiceLinkedRoleSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *ServiceLinkedRoleSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *ServiceLinkedRoleSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// ServiceLinkedRoleStatusAtProvider defines model for io.upbound.aws.iam.v1beta1.ServiceLinkedRole.status.atProvider.
type ServiceLinkedRoleStatusAtProvider struct {
	// Arn The Amazon Resource Name (ARN) specifying the role.
	Arn *string `json:"arn,omitempty"`

	// AwsServiceName The AWS service to which this role is attached. You use a string similar to a URL but without the http:// in front. For example: elasticbeanstalk.amazonaws.com. To find the full list of services that support service-linked roles, check the docs.
	AwsServiceName *string `json:"awsServiceName,omitempty"`

	// CreateDate The creation date of the IAM role.
	CreateDate *string `json:"createDate,omitempty"`

	// CustomSuffix Additional string appended to the role name. Not all AWS services support custom suffixes.
	CustomSuffix *string `json:"customSuffix,omitempty"`

	// Description The description of the role.
	Description *string `json:"description,omitempty"`

	// ID The Amazon Resource Name (ARN) of the role.
	ID *string `json:"id,omitempty"`

	// Name The name of the role.
	Name *string `json:"name,omitempty"`

	// Path The path of the role.
	Path *string `json:"path,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll *map[string]string `json:"tagsAll,omitempty"`

	// UniqueID The stable and unique string identifying the role.
	UniqueID *string `json:"uniqueId,omitempty"`
}

// ServiceLinkedRoleStatusConditionsItem A Condition that may apply to a resource.
type ServiceLinkedRoleStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// ServiceLinkedRoleStatus ServiceLinkedRoleStatus defines the observed state of ServiceLinkedRole.
type ServiceLinkedRoleStatus struct {
	AtProvider *ServiceLinkedRoleStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]ServiceLinkedRoleStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// ServiceLinkedRole ServiceLinkedRole is the Schema for the ServiceLinkedRoles API. Provides an IAM service-linked role.
type ServiceLinkedRole struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ServiceLinkedRoleAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ServiceLinkedRoleKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec ServiceLinkedRoleSpec defines the desired state of ServiceLinkedRole
	Spec *ServiceLinkedRoleSpec `json:"spec,omitempty"`

	// Status ServiceLinkedRoleStatus defines the observed state of ServiceLinkedRole.
	Status *ServiceLinkedRoleStatus `json:"status,omitempty"`
}

// IoUpboundAwsIamV1Beta1ServiceLinkedRoleList ServiceLinkedRoleList is a list of ServiceLinkedRole
type IoUpboundAwsIamV1Beta1ServiceLinkedRoleList = ServiceLinkedRoleList

// ServiceLinkedRoleList ServiceLinkedRoleList is a list of ServiceLinkedRole
type ServiceLinkedRoleList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of servicelinkedroles. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundAwsIamV1Beta1ServiceLinkedRole `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
