// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for UserLoginProfileAPIVersion.
const (
	UserLoginProfileAPIVersionIamAwsUpboundIoV1Beta1 UserLoginProfileAPIVersion = "iam.aws.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the UserLoginProfileAPIVersion enum.
func (e UserLoginProfileAPIVersion) Valid() bool {
	switch e {
	case UserLoginProfileAPIVersionIamAwsUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileKind.
const (
	UserLoginProfileKindUserLoginProfile UserLoginProfileKind = "UserLoginProfile"
)

// Valid indicates whether the value is a known member of the UserLoginProfileKind enum.
func (e UserLoginProfileKind) Valid() bool {
	switch e {
	case UserLoginProfileKindUserLoginProfile:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecDeletionPolicy.
const (
	UserLoginProfileSpecDeletionPolicyDelete UserLoginProfileSpecDeletionPolicy = "Delete"
	UserLoginProfileSpecDeletionPolicyOrphan UserLoginProfileSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecDeletionPolicy enum.
func (e UserLoginProfileSpecDeletionPolicy) Valid() bool {
	switch e {
	case UserLoginProfileSpecDeletionPolicyDelete:
		return true
	case UserLoginProfileSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecForProviderUserRefPolicyResolution.
const (
	UserLoginProfileSpecForProviderUserRefPolicyResolutionOptional UserLoginProfileSpecForProviderUserRefPolicyResolution = "Optional"
	UserLoginProfileSpecForProviderUserRefPolicyResolutionRequired UserLoginProfileSpecForProviderUserRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecForProviderUserRefPolicyResolution enum.
func (e UserLoginProfileSpecForProviderUserRefPolicyResolution) Valid() bool {
	switch e {
	case UserLoginProfileSpecForProviderUserRefPolicyResolutionOptional:
		return true
	case UserLoginProfileSpecForProviderUserRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecForProviderUserRefPolicyResolve.
const (
	UserLoginProfileSpecForProviderUserRefPolicyResolveAlways       UserLoginProfileSpecForProviderUserRefPolicyResolve = "Always"
	UserLoginProfileSpecForProviderUserRefPolicyResolveIfNotPresent UserLoginProfileSpecForProviderUserRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecForProviderUserRefPolicyResolve enum.
func (e UserLoginProfileSpecForProviderUserRefPolicyResolve) Valid() bool {
	switch e {
	case UserLoginProfileSpecForProviderUserRefPolicyResolveAlways:
		return true
	case UserLoginProfileSpecForProviderUserRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecForProviderUserSelectorPolicyResolution.
const (
	UserLoginProfileSpecForProviderUserSelectorPolicyResolutionOptional UserLoginProfileSpecForProviderUserSelectorPolicyResolution = "Optional"
	UserLoginProfileSpecForProviderUserSelectorPolicyResolutionRequired UserLoginProfileSpecForProviderUserSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecForProviderUserSelectorPolicyResolution enum.
func (e UserLoginProfileSpecForProviderUserSelectorPolicyResolution) Valid() bool {
	switch e {
	case UserLoginProfileSpecForProviderUserSelectorPolicyResolutionOptional:
		return true
	case UserLoginProfileSpecForProviderUserSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecForProviderUserSelectorPolicyResolve.
const (
	UserLoginProfileSpecForProviderUserSelectorPolicyResolveAlways       UserLoginProfileSpecForProviderUserSelectorPolicyResolve = "Always"
	UserLoginProfileSpecForProviderUserSelectorPolicyResolveIfNotPresent UserLoginProfileSpecForProviderUserSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecForProviderUserSelectorPolicyResolve enum.
func (e UserLoginProfileSpecForProviderUserSelectorPolicyResolve) Valid() bool {
	switch e {
	case UserLoginProfileSpecForProviderUserSelectorPolicyResolveAlways:
		return true
	case UserLoginProfileSpecForProviderUserSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecInitProviderUserRefPolicyResolution.
const (
	UserLoginProfileSpecInitProviderUserRefPolicyResolutionOptional UserLoginProfileSpecInitProviderUserRefPolicyResolution = "Optional"
	UserLoginProfileSpecInitProviderUserRefPolicyResolutionRequired UserLoginProfileSpecInitProviderUserRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecInitProviderUserRefPolicyResolution enum.
func (e UserLoginProfileSpecInitProviderUserRefPolicyResolution) Valid() bool {
	switch e {
	case UserLoginProfileSpecInitProviderUserRefPolicyResolutionOptional:
		return true
	case UserLoginProfileSpecInitProviderUserRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecInitProviderUserRefPolicyResolve.
const (
	UserLoginProfileSpecInitProviderUserRefPolicyResolveAlways       UserLoginProfileSpecInitProviderUserRefPolicyResolve = "Always"
	UserLoginProfileSpecInitProviderUserRefPolicyResolveIfNotPresent UserLoginProfileSpecInitProviderUserRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecInitProviderUserRefPolicyResolve enum.
func (e UserLoginProfileSpecInitProviderUserRefPolicyResolve) Valid() bool {
	switch e {
	case UserLoginProfileSpecInitProviderUserRefPolicyResolveAlways:
		return true
	case UserLoginProfileSpecInitProviderUserRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecInitProviderUserSelectorPolicyResolution.
const (
	UserLoginProfileSpecInitProviderUserSelectorPolicyResolutionOptional UserLoginProfileSpecInitProviderUserSelectorPolicyResolution = "Optional"
	UserLoginProfileSpecInitProviderUserSelectorPolicyResolutionRequired UserLoginProfileSpecInitProviderUserSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecInitProviderUserSelectorPolicyResolution enum.
func (e UserLoginProfileSpecInitProviderUserSelectorPolicyResolution) Valid() bool {
	switch e {
	case UserLoginProfileSpecInitProviderUserSelectorPolicyResolutionOptional:
		return true
	case UserLoginProfileSpecInitProviderUserSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecInitProviderUserSelectorPolicyResolve.
const (
	UserLoginProfileSpecInitProviderUserSelectorPolicyResolveAlways       UserLoginProfileSpecInitProviderUserSelectorPolicyResolve = "Always"
	UserLoginProfileSpecInitProviderUserSelectorPolicyResolveIfNotPresent UserLoginProfileSpecInitProviderUserSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecInitProviderUserSelectorPolicyResolve enum.
func (e UserLoginProfileSpecInitProviderUserSelectorPolicyResolve) Valid() bool {
	switch e {
	case UserLoginProfileSpecInitProviderUserSelectorPolicyResolveAlways:
		return true
	case UserLoginProfileSpecInitProviderUserSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecManagementPoliciesItem.
const (
	UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItem               UserLoginProfileSpecManagementPoliciesItem = "*"
	UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemCreate         UserLoginProfileSpecManagementPoliciesItem = "Create"
	UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemDelete         UserLoginProfileSpecManagementPoliciesItem = "Delete"
	UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemLateInitialize UserLoginProfileSpecManagementPoliciesItem = "LateInitialize"
	UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemObserve        UserLoginProfileSpecManagementPoliciesItem = "Observe"
	UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemUpdate         UserLoginProfileSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecManagementPoliciesItem enum.
func (e UserLoginProfileSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItem:
		return true
	case UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemCreate:
		return true
	case UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemDelete:
		return true
	case UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemLateInitialize:
		return true
	case UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemObserve:
		return true
	case UserLoginProfileSpecManagementPoliciesItemUserLoginProfileSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecProviderConfigRefPolicyResolution.
const (
	UserLoginProfileSpecProviderConfigRefPolicyResolutionOptional UserLoginProfileSpecProviderConfigRefPolicyResolution = "Optional"
	UserLoginProfileSpecProviderConfigRefPolicyResolutionRequired UserLoginProfileSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecProviderConfigRefPolicyResolution enum.
func (e UserLoginProfileSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case UserLoginProfileSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case UserLoginProfileSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for UserLoginProfileSpecProviderConfigRefPolicyResolve.
const (
	UserLoginProfileSpecProviderConfigRefPolicyResolveAlways       UserLoginProfileSpecProviderConfigRefPolicyResolve = "Always"
	UserLoginProfileSpecProviderConfigRefPolicyResolveIfNotPresent UserLoginProfileSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the UserLoginProfileSpecProviderConfigRefPolicyResolve enum.
func (e UserLoginProfileSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case UserLoginProfileSpecProviderConfigRefPolicyResolveAlways:
		return true
	case UserLoginProfileSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoUpboundAwsIamV1Beta1UserLoginProfile UserLoginProfile is the Schema for the UserLoginProfiles API. Manages an IAM User Login Profile
type IoUpboundAwsIamV1Beta1UserLoginProfile = UserLoginProfile

// UserLoginProfileAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type UserLoginProfileAPIVersion string

// UserLoginProfileKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type UserLoginProfileKind string

// UserLoginProfileSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type UserLoginProfileSpecDeletionPolicy string

// UserLoginProfileSpecForProviderUserRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type UserLoginProfileSpecForProviderUserRefPolicyResolution string

// UserLoginProfileSpecForProviderUserRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type UserLoginProfileSpecForProviderUserRefPolicyResolve string

// UserLoginProfileSpecForProviderUserRefPolicy Policies for referencing.
type UserLoginProfileSpecForProviderUserRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *UserLoginProfileSpecForProviderUserRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *UserLoginProfileSpecForProviderUserRefPolicyResolve `json:"resolve,omitempty"`
}

// UserLoginProfileSpecForProviderUserRef Reference to a User in iam to populate user.
type UserLoginProfileSpecForProviderUserRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *UserLoginProfileSpecForProviderUserRefPolicy `json:"policy,omitempty"`
}

// UserLoginProfileSpecForProviderUserSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type UserLoginProfileSpecForProviderUserSelectorPolicyResolution string

// UserLoginProfileSpecForProviderUserSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type UserLoginProfileSpecForProviderUserSelectorPolicyResolve string

// UserLoginProfileSpecForProviderUserSelectorPolicy Policies for selection.
type UserLoginProfileSpecForProviderUserSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *UserLoginProfileSpecForProviderUserSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *UserLoginProfileSpecForProviderUserSelectorPolicyResolve `json:"resolve,omitempty"`
}

// UserLoginProfileSpecForProviderUserSelector Selector for a User in iam to populate user.
type UserLoginProfileSpecForProviderUserSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *UserLoginProfileSpecForProviderUserSelectorPolicy `json:"policy,omitempty"`
}

// UserLoginProfileSpecForProvider defines model for io.upbound.aws.iam.v1beta1.UserLoginProfile.spec.forProvider.
type UserLoginProfileSpecForProvider struct {
	// PasswordLength The length of the generated password on resource creation. Only applies on resource creation. Drift detection is not possible with this argument. Default value is 20.
	PasswordLength *float32 `json:"passwordLength,omitempty"`

	// PasswordResetRequired Whether the user should be forced to reset the generated password on resource creation. Only applies on resource creation.
	PasswordResetRequired *bool `json:"passwordResetRequired,omitempty"`

	// PgpKey Either a base-64 encoded PGP public key, or a keybase username in the form keybase:username. Only applies on resource creation. Drift detection is not possible with this argument.
	PgpKey *string `json:"pgpKey,omitempty"`

	// User The IAM user's name.
	User *string `json:"user,omitempty"`

	// UserRef Reference to a User in iam to populate user.
	UserRef *UserLoginProfileSpecForProviderUserRef `json:"userRef,omitempty"`

	// UserSelector Selector for a User in iam to populate user.
	UserSelector *UserLoginProfileSpecForProviderUserSelector `json:"userSelector,omitempty"`
}

// UserLoginProfileSpecInitProviderUserRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type UserLoginProfileSpecInitProviderUserRefPolicyResolution string

// UserLoginProfileSpecInitProviderUserRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type UserLoginProfileSpecInitProviderUserRefPolicyResolve string

// UserLoginProfileSpecInitProviderUserRefPolicy Policies for referencing.
type UserLoginProfileSpecInitProviderUserRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *UserLoginProfileSpecInitProviderUserRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *UserLoginProfileSpecInitProviderUserRefPolicyResolve `json:"resolve,omitempty"`
}

// UserLoginProfileSpecInitProviderUserRef Reference to a User in iam to populate user.
type UserLoginProfileSpecInitProviderUserRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *UserLoginProfileSpecInitProviderUserRefPolicy `json:"policy,omitempty"`
}

// UserLoginProfileSpecInitProviderUserSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type UserLoginProfileSpecInitProviderUserSelectorPolicyResolution string

// UserLoginProfileSpecInitProviderUserSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type UserLoginProfileSpecInitProviderUserSelectorPolicyResolve string

// UserLoginProfileSpecInitProviderUserSelectorPolicy Policies for selection.
type UserLoginProfileSpecInitProviderUserSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *UserLoginProfileSpecInitProviderUserSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *UserLoginProfileSpecInitProviderUserSelectorPolicyResolve `json:"resolve,omitempty"`
}

// UserLoginProfileSpecInitProviderUserSelector Selector for a User in iam to populate user.
type UserLoginProfileSpecInitProviderUserSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *UserLoginProfileSpecInitProviderUserSelectorPolicy `json:"policy,omitempty"`
}

// UserLoginProfileSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type UserLoginProfileSpecInitProvider struct {
	// PasswordLength The length of the generated password on resource creation. Only applies on resource creation. Drift detection is not possible with this argument. Default value is 20.
	PasswordLength *float32 `json:"passwordLength,omitempty"`

	// PasswordResetRequired Whether the user should be forced to reset the generated password on resource creation. Only applies on resource creation.
	PasswordResetRequired *bool `json:"passwordResetRequired,omitempty"`

	// PgpKey Either a base-64 encoded PGP public key, or a keybase username in the form keybase:username. Only applies on resource creation. Drift detection is not possible with this argument.
	PgpKey *string `json:"pgpKey,omitempty"`

	// User The IAM user's name.
	User *string `json:"user,omitempty"`

	// UserRef Reference to a User in iam to populate user.
	UserRef *UserLoginProfileSpecInitProviderUserRef `json:"userRef,omitempty"`

	// UserSelector Selector for a User in iam to populate user.
	UserSelector *UserLoginProfileSpecInitProviderUserSelector `json:"userSelector,omitempty"`
}

// UserLoginProfileSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type UserLoginProfileSpecManagementPoliciesItem string

// UserLoginProfileSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type UserLoginProfileSpecProviderConfigRefPolicyResolution string

// UserLoginProfileSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type UserLoginProfileSpecProviderConfigRefPolicyResolve string

// UserLoginProfileSpecProviderConfigRefPolicy Policies for referencing.
type UserLoginProfileSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *UserLoginProfileSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *UserLoginProfileSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// UserLoginProfileSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type UserLoginProfileSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *UserLoginProfileSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// UserLoginProfileSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type UserLoginProfileSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// UserLoginProfileSpec UserLoginProfileSpec defines the desired state of UserLoginProfile
type UserLoginProfileSpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *UserLoginProfileSpecDeletionPolicy `json:"deletionPolicy,omitempty"`
	ForProvider    *UserLoginProfileSpecForProvider    `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *UserLoginProfileSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]UserLoginProfileSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *UserLoginProfileSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *UserLoginProfileSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// UserLoginProfileStatusAtProvider defines model for io.upbound.aws.iam.v1beta1.UserLoginProfile.status.atProvider.
type UserLoginProfileStatusAtProvider struct {
	// EncryptedPassword The encrypted password, base64 encoded.
	EncryptedPassword *string `json:"encryptedPassword,omitempty"`
	ID                *string `json:"id,omitempty"`

	// KeyFingerprint The fingerprint of the PGP key used to encrypt the password.
	KeyFingerprint *string `json:"keyFingerprint,omitempty"`

	// PasswordLength The length of the generated password on resource creation. Only applies on resource creation. Drift detection is not possible with this argument. Default value is 20.
	PasswordLength *float32 `json:"passwordLength,omitempty"`

	// PasswordResetRequired Whether the user should be forced to reset the generated password on resource creation. Only applies on resource creation.
	PasswordResetRequired *bool `json:"passwordResetRequired,omitempty"`

	// PgpKey Either a base-64 encoded PGP public key, or a keybase username in the form keybase:username. Only applies on resource creation. Drift detection is not possible with this argument.
	PgpKey *string `json:"pgpKey,omitempty"`

	// User The IAM user's name.
	User *string `json:"user,omitempty"`
}

// UserLoginProfileStatusConditionsItem A Condition that may apply to a resource.
type UserLoginProfileStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// UserLoginProfileStatus UserLoginProfileStatus defines the observed state of UserLoginProfile.
type UserLoginProfileStatus struct {
	AtProvider *UserLoginProfileStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]UserLoginProfileStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// UserLoginProfile UserLoginProfile is the Schema for the UserLoginProfiles API. Manages an IAM User Login Profile
type UserLoginProfile struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *UserLoginProfileAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *UserLoginProfileKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec UserLoginProfileSpec defines the desired state of UserLoginProfile
	Spec *UserLoginProfileSpec `json:"spec,omitempty"`

	// Status UserLoginProfileStatus defines the observed state of UserLoginProfile.
	Status *UserLoginProfileStatus `json:"status,omitempty"`
}

// IoUpboundAwsIamV1Beta1UserLoginProfileList UserLoginProfileList is a list of UserLoginProfile
type IoUpboundAwsIamV1Beta1UserLoginProfileList = UserLoginProfileList

// UserLoginProfileList UserLoginProfileList is a list of UserLoginProfile
type UserLoginProfileList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of userloginprofiles. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundAwsIamV1Beta1UserLoginProfile `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
