// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for VPCIpamPoolAPIVersion.
const (
	VPCIpamPoolAPIVersionEc2AwsUpboundIoV1Beta1 VPCIpamPoolAPIVersion = "ec2.aws.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolAPIVersion enum.
func (e VPCIpamPoolAPIVersion) Valid() bool {
	switch e {
	case VPCIpamPoolAPIVersionEc2AwsUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolKind.
const (
	VPCIpamPoolKindVPCIpamPool VPCIpamPoolKind = "VPCIpamPool"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolKind enum.
func (e VPCIpamPoolKind) Valid() bool {
	switch e {
	case VPCIpamPoolKindVPCIpamPool:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecDeletionPolicy.
const (
	VPCIpamPoolSpecDeletionPolicyDelete VPCIpamPoolSpecDeletionPolicy = "Delete"
	VPCIpamPoolSpecDeletionPolicyOrphan VPCIpamPoolSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecDeletionPolicy enum.
func (e VPCIpamPoolSpecDeletionPolicy) Valid() bool {
	switch e {
	case VPCIpamPoolSpecDeletionPolicyDelete:
		return true
	case VPCIpamPoolSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolution.
const (
	VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolutionOptional VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolution = "Optional"
	VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolutionRequired VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolution enum.
func (e VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolve.
const (
	VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolveAlways       VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolve = "Always"
	VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolveIfNotPresent VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolve enum.
func (e VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolution.
const (
	VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolutionOptional VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolution = "Optional"
	VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolutionRequired VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolution enum.
func (e VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolve.
const (
	VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolveAlways       VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolve = "Always"
	VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolveIfNotPresent VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolve enum.
func (e VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolution.
const (
	VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolutionOptional VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolution = "Optional"
	VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolutionRequired VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolution enum.
func (e VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolve.
const (
	VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolveAlways       VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolve = "Always"
	VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolveIfNotPresent VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolve enum.
func (e VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolution.
const (
	VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolutionOptional VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolution = "Optional"
	VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolutionRequired VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolution enum.
func (e VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolve.
const (
	VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolveAlways       VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolve = "Always"
	VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolveIfNotPresent VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolve enum.
func (e VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolution.
const (
	VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolutionOptional VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolution = "Optional"
	VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolutionRequired VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolution enum.
func (e VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolve.
const (
	VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolveAlways       VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolve = "Always"
	VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolveIfNotPresent VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolve enum.
func (e VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolution.
const (
	VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolutionOptional VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolution = "Optional"
	VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolutionRequired VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolution enum.
func (e VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolve.
const (
	VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolveAlways       VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolve = "Always"
	VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolveIfNotPresent VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolve enum.
func (e VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolution.
const (
	VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolutionOptional VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolution = "Optional"
	VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolutionRequired VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolution enum.
func (e VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolve.
const (
	VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolveAlways       VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolve = "Always"
	VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolveIfNotPresent VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolve enum.
func (e VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolution.
const (
	VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolutionOptional VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolution = "Optional"
	VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolutionRequired VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolution enum.
func (e VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolve.
const (
	VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolveAlways       VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolve = "Always"
	VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolveIfNotPresent VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolve enum.
func (e VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolution.
const (
	VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolutionOptional VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolution = "Optional"
	VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolutionRequired VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolution enum.
func (e VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolve.
const (
	VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolveAlways       VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolve = "Always"
	VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolveIfNotPresent VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolve enum.
func (e VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolution.
const (
	VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolutionOptional VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolution = "Optional"
	VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolutionRequired VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolution enum.
func (e VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolve.
const (
	VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolveAlways       VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolve = "Always"
	VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolveIfNotPresent VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolve enum.
func (e VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolution.
const (
	VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolutionOptional VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolution = "Optional"
	VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolutionRequired VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolution enum.
func (e VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolve.
const (
	VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolveAlways       VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolve = "Always"
	VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolveIfNotPresent VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolve enum.
func (e VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolution.
const (
	VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolutionOptional VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolution = "Optional"
	VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolutionRequired VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolution enum.
func (e VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolve.
const (
	VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolveAlways       VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolve = "Always"
	VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolveIfNotPresent VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolve enum.
func (e VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecManagementPoliciesItem.
const (
	VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItem               VPCIpamPoolSpecManagementPoliciesItem = "*"
	VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemCreate         VPCIpamPoolSpecManagementPoliciesItem = "Create"
	VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemDelete         VPCIpamPoolSpecManagementPoliciesItem = "Delete"
	VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemLateInitialize VPCIpamPoolSpecManagementPoliciesItem = "LateInitialize"
	VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemObserve        VPCIpamPoolSpecManagementPoliciesItem = "Observe"
	VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemUpdate         VPCIpamPoolSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecManagementPoliciesItem enum.
func (e VPCIpamPoolSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItem:
		return true
	case VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemCreate:
		return true
	case VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemDelete:
		return true
	case VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemLateInitialize:
		return true
	case VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemObserve:
		return true
	case VPCIpamPoolSpecManagementPoliciesItemVPCIpamPoolSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecProviderConfigRefPolicyResolution.
const (
	VPCIpamPoolSpecProviderConfigRefPolicyResolutionOptional VPCIpamPoolSpecProviderConfigRefPolicyResolution = "Optional"
	VPCIpamPoolSpecProviderConfigRefPolicyResolutionRequired VPCIpamPoolSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecProviderConfigRefPolicyResolution enum.
func (e VPCIpamPoolSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case VPCIpamPoolSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case VPCIpamPoolSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for VPCIpamPoolSpecProviderConfigRefPolicyResolve.
const (
	VPCIpamPoolSpecProviderConfigRefPolicyResolveAlways       VPCIpamPoolSpecProviderConfigRefPolicyResolve = "Always"
	VPCIpamPoolSpecProviderConfigRefPolicyResolveIfNotPresent VPCIpamPoolSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the VPCIpamPoolSpecProviderConfigRefPolicyResolve enum.
func (e VPCIpamPoolSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case VPCIpamPoolSpecProviderConfigRefPolicyResolveAlways:
		return true
	case VPCIpamPoolSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoUpboundAwsEc2V1Beta1VPCIpamPool VPCIpamPool is the Schema for the VPCIpamPools API. Provides a IP address pool resource for IPAM.
type IoUpboundAwsEc2V1Beta1VPCIpamPool = VPCIpamPool

// VPCIpamPoolAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type VPCIpamPoolAPIVersion string

// VPCIpamPoolKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type VPCIpamPoolKind string

// VPCIpamPoolSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type VPCIpamPoolSpecDeletionPolicy string

// VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolution string

// VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolve string

// VPCIpamPoolSpecForProviderIpamScopeIDRefPolicy Policies for referencing.
type VPCIpamPoolSpecForProviderIpamScopeIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecForProviderIpamScopeIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecForProviderIpamScopeIDRef Reference to a VPCIpamScope in ec2 to populate ipamScopeId.
type VPCIpamPoolSpecForProviderIpamScopeIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *VPCIpamPoolSpecForProviderIpamScopeIDRefPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolution string

// VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolve string

// VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicy Policies for selection.
type VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecForProviderIpamScopeIDSelector Selector for a VPCIpamScope in ec2 to populate ipamScopeId.
type VPCIpamPoolSpecForProviderIpamScopeIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *VPCIpamPoolSpecForProviderIpamScopeIDSelectorPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolution string

// VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolve string

// VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicy Policies for referencing.
type VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecForProviderSourceIpamPoolIDRef Reference to a VPCIpamPool in ec2 to populate sourceIpamPoolId.
type VPCIpamPoolSpecForProviderSourceIpamPoolIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *VPCIpamPoolSpecForProviderSourceIpamPoolIDRefPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolution string

// VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolve string

// VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicy Policies for selection.
type VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecForProviderSourceIpamPoolIDSelector Selector for a VPCIpamPool in ec2 to populate sourceIpamPoolId.
type VPCIpamPoolSpecForProviderSourceIpamPoolIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *VPCIpamPoolSpecForProviderSourceIpamPoolIDSelectorPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolution string

// VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolve string

// VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicy Policies for referencing.
type VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecForProviderSourceResourceResourceIDRef Reference to a VPC in ec2 to populate resourceId.
type VPCIpamPoolSpecForProviderSourceResourceResourceIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *VPCIpamPoolSpecForProviderSourceResourceResourceIDRefPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolution string

// VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolve string

// VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicy Policies for selection.
type VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecForProviderSourceResourceResourceIDSelector Selector for a VPC in ec2 to populate resourceId.
type VPCIpamPoolSpecForProviderSourceResourceResourceIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *VPCIpamPoolSpecForProviderSourceResourceResourceIDSelectorPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecForProviderSourceResource Resource to use to use to configure a resource planning IPAM Pool. If configured, the locale of the parent pool must match the region that the vpc resides in.
type VPCIpamPoolSpecForProviderSourceResource struct {
	// ResourceID ID of the resource.
	ResourceID *string `json:"resourceId,omitempty"`

	// ResourceIDRef Reference to a VPC in ec2 to populate resourceId.
	ResourceIDRef *VPCIpamPoolSpecForProviderSourceResourceResourceIDRef `json:"resourceIdRef,omitempty"`

	// ResourceIDSelector Selector for a VPC in ec2 to populate resourceId.
	ResourceIDSelector *VPCIpamPoolSpecForProviderSourceResourceResourceIDSelector `json:"resourceIdSelector,omitempty"`

	// ResourceOwner Owner of the resource.
	ResourceOwner *string `json:"resourceOwner,omitempty"`

	// ResourceRegion Region where the resource exists. Must match the locale of the parent IPAM Pool.
	ResourceRegion *string `json:"resourceRegion,omitempty"`

	// ResourceType Type of the resource. (vpc)
	ResourceType *string `json:"resourceType,omitempty"`
}

// VPCIpamPoolSpecForProvider defines model for io.upbound.aws.ec2.v1beta1.VPCIpamPool.spec.forProvider.
type VPCIpamPoolSpecForProvider struct {
	// AddressFamily The IP protocol assigned to this pool. You must choose either IPv4 or IPv6 protocol for a pool.
	AddressFamily *string `json:"addressFamily,omitempty"`

	// AllocationDefaultNetmaskLength A default netmask length for allocations added to this pool. If, for example, the CIDR assigned to this pool is 10.0.0.0/8 and you enter 16 here, new allocations will default to 10.0.0.0/16 (unless you provide a different netmask value when you create the new allocation).
	AllocationDefaultNetmaskLength *float32 `json:"allocationDefaultNetmaskLength,omitempty"`

	// AllocationMaxNetmaskLength The maximum netmask length that will be required for CIDR allocations in this pool.
	AllocationMaxNetmaskLength *float32 `json:"allocationMaxNetmaskLength,omitempty"`

	// AllocationMinNetmaskLength The minimum netmask length that will be required for CIDR allocations in this pool.
	AllocationMinNetmaskLength *float32 `json:"allocationMinNetmaskLength,omitempty"`

	// AllocationResourceTags Tags that are required for resources that use CIDRs from this IPAM pool. Resources that do not have these tags will not be allowed to allocate space from the pool. If the resources have their tags changed after they have allocated space or if the allocation tagging requirements are changed on the pool, the resource may be marked as noncompliant.
	AllocationResourceTags *map[string]string `json:"allocationResourceTags,omitempty"`

	// AutoImport If you include this argument, IPAM automatically imports any VPCs you have in your scope that fall
	// within the CIDR range in the pool.
	AutoImport *bool `json:"autoImport,omitempty"`

	// AwsService Limits which AWS service the pool can be used in. Only useable on public scopes. Valid Values: ec2.
	AwsService *string `json:"awsService,omitempty"`

	// Cascade Enables you to quickly delete an IPAM pool and all resources within that pool, including provisioned CIDRs, allocations, and other pools.
	Cascade *bool `json:"cascade,omitempty"`

	// Description A description for the IPAM pool.
	Description *string `json:"description,omitempty"`

	// IpamScopeID The ID of the scope in which you would like to create the IPAM pool.
	IpamScopeID *string `json:"ipamScopeId,omitempty"`

	// IpamScopeIDRef Reference to a VPCIpamScope in ec2 to populate ipamScopeId.
	IpamScopeIDRef *VPCIpamPoolSpecForProviderIpamScopeIDRef `json:"ipamScopeIdRef,omitempty"`

	// IpamScopeIDSelector Selector for a VPCIpamScope in ec2 to populate ipamScopeId.
	IpamScopeIDSelector *VPCIpamPoolSpecForProviderIpamScopeIDSelector `json:"ipamScopeIdSelector,omitempty"`

	// Locale The locale in which you would like to create the IPAM pool. Locale is the Region where you want to make an IPAM pool available for allocations. You can only create pools with locales that match the operating Regions of the IPAM. You can only create VPCs from a pool whose locale matches the VPC's Region. Possible values: Any AWS region, such as us-east-1.
	Locale *string `json:"locale,omitempty"`

	// PublicIPSource The IP address source for pools in the public scope. Only used for provisioning IP address CIDRs to pools in the public scope. Valid values are byoip or amazon. Default is byoip.
	PublicIPSource *string `json:"publicIpSource,omitempty"`

	// PubliclyAdvertisable Defines whether or not IPv6 pool space is publicly advertisable over the internet. This argument is required if address_family = "ipv6" and public_ip_source = "byoip", default is false. This option is not available for IPv4 pool space or if public_ip_source = "amazon". Setting this argument to true when it is not available may result in erroneous differences being reported.
	PubliclyAdvertisable *bool `json:"publiclyAdvertisable,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// SourceIpamPoolID The ID of the source IPAM pool. Use this argument to create a child pool within an existing pool.
	SourceIpamPoolID *string `json:"sourceIpamPoolId,omitempty"`

	// SourceIpamPoolIDRef Reference to a VPCIpamPool in ec2 to populate sourceIpamPoolId.
	SourceIpamPoolIDRef *VPCIpamPoolSpecForProviderSourceIpamPoolIDRef `json:"sourceIpamPoolIdRef,omitempty"`

	// SourceIpamPoolIDSelector Selector for a VPCIpamPool in ec2 to populate sourceIpamPoolId.
	SourceIpamPoolIDSelector *VPCIpamPoolSpecForProviderSourceIpamPoolIDSelector `json:"sourceIpamPoolIdSelector,omitempty"`

	// SourceResource Resource to use to use to configure a resource planning IPAM Pool. If configured, the locale of the parent pool must match the region that the vpc resides in.
	SourceResource *VPCIpamPoolSpecForProviderSourceResource `json:"sourceResource,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolution string

// VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolve string

// VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicy Policies for referencing.
type VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecInitProviderIpamScopeIDRef Reference to a VPCIpamScope in ec2 to populate ipamScopeId.
type VPCIpamPoolSpecInitProviderIpamScopeIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *VPCIpamPoolSpecInitProviderIpamScopeIDRefPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolution string

// VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolve string

// VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicy Policies for selection.
type VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecInitProviderIpamScopeIDSelector Selector for a VPCIpamScope in ec2 to populate ipamScopeId.
type VPCIpamPoolSpecInitProviderIpamScopeIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *VPCIpamPoolSpecInitProviderIpamScopeIDSelectorPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolution string

// VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolve string

// VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicy Policies for referencing.
type VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecInitProviderSourceIpamPoolIDRef Reference to a VPCIpamPool in ec2 to populate sourceIpamPoolId.
type VPCIpamPoolSpecInitProviderSourceIpamPoolIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *VPCIpamPoolSpecInitProviderSourceIpamPoolIDRefPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolution string

// VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolve string

// VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicy Policies for selection.
type VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelector Selector for a VPCIpamPool in ec2 to populate sourceIpamPoolId.
type VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelectorPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolution string

// VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolve string

// VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicy Policies for referencing.
type VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecInitProviderSourceResourceResourceIDRef Reference to a VPC in ec2 to populate resourceId.
type VPCIpamPoolSpecInitProviderSourceResourceResourceIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *VPCIpamPoolSpecInitProviderSourceResourceResourceIDRefPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolution string

// VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolve string

// VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicy Policies for selection.
type VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelector Selector for a VPC in ec2 to populate resourceId.
type VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelectorPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecInitProviderSourceResource Resource to use to use to configure a resource planning IPAM Pool. If configured, the locale of the parent pool must match the region that the vpc resides in.
type VPCIpamPoolSpecInitProviderSourceResource struct {
	// ResourceID ID of the resource.
	ResourceID *string `json:"resourceId,omitempty"`

	// ResourceIDRef Reference to a VPC in ec2 to populate resourceId.
	ResourceIDRef *VPCIpamPoolSpecInitProviderSourceResourceResourceIDRef `json:"resourceIdRef,omitempty"`

	// ResourceIDSelector Selector for a VPC in ec2 to populate resourceId.
	ResourceIDSelector *VPCIpamPoolSpecInitProviderSourceResourceResourceIDSelector `json:"resourceIdSelector,omitempty"`

	// ResourceOwner Owner of the resource.
	ResourceOwner *string `json:"resourceOwner,omitempty"`

	// ResourceRegion Region where the resource exists. Must match the locale of the parent IPAM Pool.
	ResourceRegion *string `json:"resourceRegion,omitempty"`

	// ResourceType Type of the resource. (vpc)
	ResourceType *string `json:"resourceType,omitempty"`
}

// VPCIpamPoolSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type VPCIpamPoolSpecInitProvider struct {
	// AddressFamily The IP protocol assigned to this pool. You must choose either IPv4 or IPv6 protocol for a pool.
	AddressFamily *string `json:"addressFamily,omitempty"`

	// AllocationDefaultNetmaskLength A default netmask length for allocations added to this pool. If, for example, the CIDR assigned to this pool is 10.0.0.0/8 and you enter 16 here, new allocations will default to 10.0.0.0/16 (unless you provide a different netmask value when you create the new allocation).
	AllocationDefaultNetmaskLength *float32 `json:"allocationDefaultNetmaskLength,omitempty"`

	// AllocationMaxNetmaskLength The maximum netmask length that will be required for CIDR allocations in this pool.
	AllocationMaxNetmaskLength *float32 `json:"allocationMaxNetmaskLength,omitempty"`

	// AllocationMinNetmaskLength The minimum netmask length that will be required for CIDR allocations in this pool.
	AllocationMinNetmaskLength *float32 `json:"allocationMinNetmaskLength,omitempty"`

	// AllocationResourceTags Tags that are required for resources that use CIDRs from this IPAM pool. Resources that do not have these tags will not be allowed to allocate space from the pool. If the resources have their tags changed after they have allocated space or if the allocation tagging requirements are changed on the pool, the resource may be marked as noncompliant.
	AllocationResourceTags *map[string]string `json:"allocationResourceTags,omitempty"`

	// AutoImport If you include this argument, IPAM automatically imports any VPCs you have in your scope that fall
	// within the CIDR range in the pool.
	AutoImport *bool `json:"autoImport,omitempty"`

	// AwsService Limits which AWS service the pool can be used in. Only useable on public scopes. Valid Values: ec2.
	AwsService *string `json:"awsService,omitempty"`

	// Cascade Enables you to quickly delete an IPAM pool and all resources within that pool, including provisioned CIDRs, allocations, and other pools.
	Cascade *bool `json:"cascade,omitempty"`

	// Description A description for the IPAM pool.
	Description *string `json:"description,omitempty"`

	// IpamScopeID The ID of the scope in which you would like to create the IPAM pool.
	IpamScopeID *string `json:"ipamScopeId,omitempty"`

	// IpamScopeIDRef Reference to a VPCIpamScope in ec2 to populate ipamScopeId.
	IpamScopeIDRef *VPCIpamPoolSpecInitProviderIpamScopeIDRef `json:"ipamScopeIdRef,omitempty"`

	// IpamScopeIDSelector Selector for a VPCIpamScope in ec2 to populate ipamScopeId.
	IpamScopeIDSelector *VPCIpamPoolSpecInitProviderIpamScopeIDSelector `json:"ipamScopeIdSelector,omitempty"`

	// Locale The locale in which you would like to create the IPAM pool. Locale is the Region where you want to make an IPAM pool available for allocations. You can only create pools with locales that match the operating Regions of the IPAM. You can only create VPCs from a pool whose locale matches the VPC's Region. Possible values: Any AWS region, such as us-east-1.
	Locale *string `json:"locale,omitempty"`

	// PublicIPSource The IP address source for pools in the public scope. Only used for provisioning IP address CIDRs to pools in the public scope. Valid values are byoip or amazon. Default is byoip.
	PublicIPSource *string `json:"publicIpSource,omitempty"`

	// PubliclyAdvertisable Defines whether or not IPv6 pool space is publicly advertisable over the internet. This argument is required if address_family = "ipv6" and public_ip_source = "byoip", default is false. This option is not available for IPv4 pool space or if public_ip_source = "amazon". Setting this argument to true when it is not available may result in erroneous differences being reported.
	PubliclyAdvertisable *bool `json:"publiclyAdvertisable,omitempty"`

	// SourceIpamPoolID The ID of the source IPAM pool. Use this argument to create a child pool within an existing pool.
	SourceIpamPoolID *string `json:"sourceIpamPoolId,omitempty"`

	// SourceIpamPoolIDRef Reference to a VPCIpamPool in ec2 to populate sourceIpamPoolId.
	SourceIpamPoolIDRef *VPCIpamPoolSpecInitProviderSourceIpamPoolIDRef `json:"sourceIpamPoolIdRef,omitempty"`

	// SourceIpamPoolIDSelector Selector for a VPCIpamPool in ec2 to populate sourceIpamPoolId.
	SourceIpamPoolIDSelector *VPCIpamPoolSpecInitProviderSourceIpamPoolIDSelector `json:"sourceIpamPoolIdSelector,omitempty"`

	// SourceResource Resource to use to use to configure a resource planning IPAM Pool. If configured, the locale of the parent pool must match the region that the vpc resides in.
	SourceResource *VPCIpamPoolSpecInitProviderSourceResource `json:"sourceResource,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// VPCIpamPoolSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type VPCIpamPoolSpecManagementPoliciesItem string

// VPCIpamPoolSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type VPCIpamPoolSpecProviderConfigRefPolicyResolution string

// VPCIpamPoolSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type VPCIpamPoolSpecProviderConfigRefPolicyResolve string

// VPCIpamPoolSpecProviderConfigRefPolicy Policies for referencing.
type VPCIpamPoolSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *VPCIpamPoolSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *VPCIpamPoolSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// VPCIpamPoolSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type VPCIpamPoolSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *VPCIpamPoolSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// VPCIpamPoolSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type VPCIpamPoolSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// VPCIpamPoolSpec VPCIpamPoolSpec defines the desired state of VPCIpamPool
type VPCIpamPoolSpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *VPCIpamPoolSpecDeletionPolicy `json:"deletionPolicy,omitempty"`
	ForProvider    *VPCIpamPoolSpecForProvider    `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *VPCIpamPoolSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]VPCIpamPoolSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *VPCIpamPoolSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *VPCIpamPoolSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// VPCIpamPoolStatusAtProviderSourceResource Resource to use to use to configure a resource planning IPAM Pool. If configured, the locale of the parent pool must match the region that the vpc resides in.
type VPCIpamPoolStatusAtProviderSourceResource struct {
	// ResourceID ID of the resource.
	ResourceID *string `json:"resourceId,omitempty"`

	// ResourceOwner Owner of the resource.
	ResourceOwner *string `json:"resourceOwner,omitempty"`

	// ResourceRegion Region where the resource exists. Must match the locale of the parent IPAM Pool.
	ResourceRegion *string `json:"resourceRegion,omitempty"`

	// ResourceType Type of the resource. (vpc)
	ResourceType *string `json:"resourceType,omitempty"`
}

// VPCIpamPoolStatusAtProvider defines model for io.upbound.aws.ec2.v1beta1.VPCIpamPool.status.atProvider.
type VPCIpamPoolStatusAtProvider struct {
	// AddressFamily The IP protocol assigned to this pool. You must choose either IPv4 or IPv6 protocol for a pool.
	AddressFamily *string `json:"addressFamily,omitempty"`

	// AllocationDefaultNetmaskLength A default netmask length for allocations added to this pool. If, for example, the CIDR assigned to this pool is 10.0.0.0/8 and you enter 16 here, new allocations will default to 10.0.0.0/16 (unless you provide a different netmask value when you create the new allocation).
	AllocationDefaultNetmaskLength *float32 `json:"allocationDefaultNetmaskLength,omitempty"`

	// AllocationMaxNetmaskLength The maximum netmask length that will be required for CIDR allocations in this pool.
	AllocationMaxNetmaskLength *float32 `json:"allocationMaxNetmaskLength,omitempty"`

	// AllocationMinNetmaskLength The minimum netmask length that will be required for CIDR allocations in this pool.
	AllocationMinNetmaskLength *float32 `json:"allocationMinNetmaskLength,omitempty"`

	// AllocationResourceTags Tags that are required for resources that use CIDRs from this IPAM pool. Resources that do not have these tags will not be allowed to allocate space from the pool. If the resources have their tags changed after they have allocated space or if the allocation tagging requirements are changed on the pool, the resource may be marked as noncompliant.
	AllocationResourceTags *map[string]string `json:"allocationResourceTags,omitempty"`

	// Arn Amazon Resource Name (ARN) of IPAM
	Arn *string `json:"arn,omitempty"`

	// AutoImport If you include this argument, IPAM automatically imports any VPCs you have in your scope that fall
	// within the CIDR range in the pool.
	AutoImport *bool `json:"autoImport,omitempty"`

	// AwsService Limits which AWS service the pool can be used in. Only useable on public scopes. Valid Values: ec2.
	AwsService *string `json:"awsService,omitempty"`

	// Cascade Enables you to quickly delete an IPAM pool and all resources within that pool, including provisioned CIDRs, allocations, and other pools.
	Cascade *bool `json:"cascade,omitempty"`

	// Description A description for the IPAM pool.
	Description *string `json:"description,omitempty"`

	// ID The ID of the IPAM
	ID *string `json:"id,omitempty"`

	// IpamScopeID The ID of the scope in which you would like to create the IPAM pool.
	IpamScopeID   *string `json:"ipamScopeId,omitempty"`
	IpamScopeType *string `json:"ipamScopeType,omitempty"`

	// Locale The locale in which you would like to create the IPAM pool. Locale is the Region where you want to make an IPAM pool available for allocations. You can only create pools with locales that match the operating Regions of the IPAM. You can only create VPCs from a pool whose locale matches the VPC's Region. Possible values: Any AWS region, such as us-east-1.
	Locale    *string  `json:"locale,omitempty"`
	PoolDepth *float32 `json:"poolDepth,omitempty"`

	// PublicIPSource The IP address source for pools in the public scope. Only used for provisioning IP address CIDRs to pools in the public scope. Valid values are byoip or amazon. Default is byoip.
	PublicIPSource *string `json:"publicIpSource,omitempty"`

	// PubliclyAdvertisable Defines whether or not IPv6 pool space is publicly advertisable over the internet. This argument is required if address_family = "ipv6" and public_ip_source = "byoip", default is false. This option is not available for IPv4 pool space or if public_ip_source = "amazon". Setting this argument to true when it is not available may result in erroneous differences being reported.
	PubliclyAdvertisable *bool `json:"publiclyAdvertisable,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// SourceIpamPoolID The ID of the source IPAM pool. Use this argument to create a child pool within an existing pool.
	SourceIpamPoolID *string `json:"sourceIpamPoolId,omitempty"`

	// SourceResource Resource to use to use to configure a resource planning IPAM Pool. If configured, the locale of the parent pool must match the region that the vpc resides in.
	SourceResource *VPCIpamPoolStatusAtProviderSourceResource `json:"sourceResource,omitempty"`

	// State The ID of the IPAM
	State *string `json:"state,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll *map[string]string `json:"tagsAll,omitempty"`
}

// VPCIpamPoolStatusConditionsItem A Condition that may apply to a resource.
type VPCIpamPoolStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// VPCIpamPoolStatus VPCIpamPoolStatus defines the observed state of VPCIpamPool.
type VPCIpamPoolStatus struct {
	AtProvider *VPCIpamPoolStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]VPCIpamPoolStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// VPCIpamPool VPCIpamPool is the Schema for the VPCIpamPools API. Provides a IP address pool resource for IPAM.
type VPCIpamPool struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *VPCIpamPoolAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *VPCIpamPoolKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec VPCIpamPoolSpec defines the desired state of VPCIpamPool
	Spec *VPCIpamPoolSpec `json:"spec,omitempty"`

	// Status VPCIpamPoolStatus defines the observed state of VPCIpamPool.
	Status *VPCIpamPoolStatus `json:"status,omitempty"`
}

// IoUpboundAwsEc2V1Beta1VPCIpamPoolList VPCIpamPoolList is a list of VPCIpamPool
type IoUpboundAwsEc2V1Beta1VPCIpamPoolList = VPCIpamPoolList

// VPCIpamPoolList VPCIpamPoolList is a list of VPCIpamPool
type VPCIpamPoolList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of vpcipampools. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundAwsEc2V1Beta1VPCIpamPool `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
