// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for SpotInstanceRequestAPIVersion.
const (
	SpotInstanceRequestAPIVersionEc2AwsMUpboundIoV1Beta1 SpotInstanceRequestAPIVersion = "ec2.aws.m.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestAPIVersion enum.
func (e SpotInstanceRequestAPIVersion) Valid() bool {
	switch e {
	case SpotInstanceRequestAPIVersionEc2AwsMUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestKind.
const (
	SpotInstanceRequestKindSpotInstanceRequest SpotInstanceRequestKind = "SpotInstanceRequest"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestKind enum.
func (e SpotInstanceRequestKind) Valid() bool {
	switch e {
	case SpotInstanceRequestKindSpotInstanceRequest:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolution.
const (
	SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolutionOptional SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolution = "Optional"
	SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolutionRequired SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolution enum.
func (e SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolution) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolutionOptional:
		return true
	case SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolve.
const (
	SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolveAlways       SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolve = "Always"
	SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolveIfNotPresent SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolve enum.
func (e SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolve) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolveAlways:
		return true
	case SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolution.
const (
	SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolutionOptional SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolution = "Optional"
	SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolutionRequired SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolution enum.
func (e SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolutionOptional:
		return true
	case SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolve.
const (
	SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolveAlways       SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolve = "Always"
	SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolveIfNotPresent SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolve enum.
func (e SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolveAlways:
		return true
	case SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolution.
const (
	SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolutionOptional SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolution = "Optional"
	SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolutionRequired SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolution enum.
func (e SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolution) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolutionOptional:
		return true
	case SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolve.
const (
	SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolveAlways       SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolve = "Always"
	SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolveIfNotPresent SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolve enum.
func (e SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolve) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolveAlways:
		return true
	case SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolution.
const (
	SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolutionOptional SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolution = "Optional"
	SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolutionRequired SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolution enum.
func (e SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolutionOptional:
		return true
	case SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolve.
const (
	SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolveAlways       SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolve = "Always"
	SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolveIfNotPresent SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolve enum.
func (e SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolveAlways:
		return true
	case SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolution.
const (
	SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolutionOptional SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolution = "Optional"
	SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolutionRequired SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolution enum.
func (e SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolution) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolutionOptional:
		return true
	case SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolve.
const (
	SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolveAlways       SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolve = "Always"
	SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolveIfNotPresent SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolve enum.
func (e SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolve) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolveAlways:
		return true
	case SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolution.
const (
	SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolutionOptional SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolution = "Optional"
	SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolutionRequired SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolution enum.
func (e SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolutionOptional:
		return true
	case SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolve.
const (
	SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolveAlways       SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolve = "Always"
	SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolveIfNotPresent SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolve enum.
func (e SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolveAlways:
		return true
	case SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolution.
const (
	SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolutionOptional SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolution = "Optional"
	SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolutionRequired SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolution enum.
func (e SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolution) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolutionOptional:
		return true
	case SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolve.
const (
	SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolveAlways       SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolve = "Always"
	SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolveIfNotPresent SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolve enum.
func (e SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolve) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolveAlways:
		return true
	case SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolution.
const (
	SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolutionOptional SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolution = "Optional"
	SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolutionRequired SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolution enum.
func (e SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolutionOptional:
		return true
	case SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolve.
const (
	SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolveAlways       SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolve = "Always"
	SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolveIfNotPresent SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolve enum.
func (e SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolveAlways:
		return true
	case SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for SpotInstanceRequestSpecManagementPoliciesItem.
const (
	SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItem               SpotInstanceRequestSpecManagementPoliciesItem = "*"
	SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemCreate         SpotInstanceRequestSpecManagementPoliciesItem = "Create"
	SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemDelete         SpotInstanceRequestSpecManagementPoliciesItem = "Delete"
	SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemLateInitialize SpotInstanceRequestSpecManagementPoliciesItem = "LateInitialize"
	SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemObserve        SpotInstanceRequestSpecManagementPoliciesItem = "Observe"
	SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemUpdate         SpotInstanceRequestSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the SpotInstanceRequestSpecManagementPoliciesItem enum.
func (e SpotInstanceRequestSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItem:
		return true
	case SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemCreate:
		return true
	case SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemDelete:
		return true
	case SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemLateInitialize:
		return true
	case SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemObserve:
		return true
	case SpotInstanceRequestSpecManagementPoliciesItemSpotInstanceRequestSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoUpboundMAwsEc2V1Beta1SpotInstanceRequest SpotInstanceRequest is the Schema for the SpotInstanceRequests API. Provides a Spot Instance Request resource.
type IoUpboundMAwsEc2V1Beta1SpotInstanceRequest = SpotInstanceRequest

// SpotInstanceRequestAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type SpotInstanceRequestAPIVersion string

// SpotInstanceRequestKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type SpotInstanceRequestKind string

// SpotInstanceRequestSpecForProviderCapacityReservationSpecificationCapacityReservationTarget defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.capacityReservationSpecification.capacityReservationTarget.
type SpotInstanceRequestSpecForProviderCapacityReservationSpecificationCapacityReservationTarget struct {
	// CapacityReservationID The Spot Instance Request ID.
	CapacityReservationID               *string `json:"capacityReservationId,omitempty"`
	CapacityReservationResourceGroupArn *string `json:"capacityReservationResourceGroupArn,omitempty"`
}

// SpotInstanceRequestSpecForProviderCapacityReservationSpecification defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.capacityReservationSpecification.
type SpotInstanceRequestSpecForProviderCapacityReservationSpecification struct {
	CapacityReservationPreference *string                                                                                      `json:"capacityReservationPreference,omitempty"`
	CapacityReservationTarget     *SpotInstanceRequestSpecForProviderCapacityReservationSpecificationCapacityReservationTarget `json:"capacityReservationTarget,omitempty"`
}

// SpotInstanceRequestSpecForProviderCPUOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.cpuOptions.
type SpotInstanceRequestSpecForProviderCPUOptions struct {
	AmdSevSnp            *string  `json:"amdSevSnp,omitempty"`
	CoreCount            *float32 `json:"coreCount,omitempty"`
	NestedVirtualization *string  `json:"nestedVirtualization,omitempty"`
	ThreadsPerCore       *float32 `json:"threadsPerCore,omitempty"`
}

// SpotInstanceRequestSpecForProviderCreditSpecification defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.creditSpecification.
type SpotInstanceRequestSpecForProviderCreditSpecification struct {
	CPUCredits *string `json:"cpuCredits,omitempty"`
}

// SpotInstanceRequestSpecForProviderEbsBlockDeviceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.ebsBlockDevice.
type SpotInstanceRequestSpecForProviderEbsBlockDeviceItem struct {
	DeleteOnTermination *bool    `json:"deleteOnTermination,omitempty"`
	DeviceName          *string  `json:"deviceName,omitempty"`
	Encrypted           *bool    `json:"encrypted,omitempty"`
	Iops                *float32 `json:"iops,omitempty"`

	// KmsKeyID The Spot Instance Request ID.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`

	// SnapshotID The Spot Instance Request ID.
	SnapshotID *string `json:"snapshotId,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll    *map[string]string `json:"tagsAll,omitempty"`
	Throughput *float32           `json:"throughput,omitempty"`
	VolumeSize *float32           `json:"volumeSize,omitempty"`
	VolumeType *string            `json:"volumeType,omitempty"`
}

// SpotInstanceRequestSpecForProviderEnclaveOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.enclaveOptions.
type SpotInstanceRequestSpecForProviderEnclaveOptions struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// SpotInstanceRequestSpecForProviderEphemeralBlockDeviceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.ephemeralBlockDevice.
type SpotInstanceRequestSpecForProviderEphemeralBlockDeviceItem struct {
	DeviceName  *string `json:"deviceName,omitempty"`
	NoDevice    *bool   `json:"noDevice,omitempty"`
	VirtualName *string `json:"virtualName,omitempty"`
}

// SpotInstanceRequestSpecForProviderLaunchTemplate defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.launchTemplate.
type SpotInstanceRequestSpecForProviderLaunchTemplate struct {
	// ID The Spot Instance Request ID.
	ID      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

// SpotInstanceRequestSpecForProviderMaintenanceOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.maintenanceOptions.
type SpotInstanceRequestSpecForProviderMaintenanceOptions struct {
	AutoRecovery *string `json:"autoRecovery,omitempty"`
}

// SpotInstanceRequestSpecForProviderMetadataOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.metadataOptions.
type SpotInstanceRequestSpecForProviderMetadataOptions struct {
	HTTPEndpoint            *string  `json:"httpEndpoint,omitempty"`
	HTTPProtocolIpv6        *string  `json:"httpProtocolIpv6,omitempty"`
	HTTPPutResponseHopLimit *float32 `json:"httpPutResponseHopLimit,omitempty"`
	HTTPTokens              *string  `json:"httpTokens,omitempty"`

	// InstanceMetadataTags Key-value map of resource tags.
	InstanceMetadataTags *string `json:"instanceMetadataTags,omitempty"`
}

// SpotInstanceRequestSpecForProviderNetworkInterfaceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.networkInterface.
type SpotInstanceRequestSpecForProviderNetworkInterfaceItem struct {
	DeleteOnTermination *bool    `json:"deleteOnTermination,omitempty"`
	DeviceIndex         *float32 `json:"deviceIndex,omitempty"`

	// NetworkInterfaceID The Spot Instance Request ID.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty"`
}

// SpotInstanceRequestSpecForProviderPrivateDNSNameOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.privateDnsNameOptions.
type SpotInstanceRequestSpecForProviderPrivateDNSNameOptions struct {
	EnableResourceNameDNSARecord    *bool   `json:"enableResourceNameDnsARecord,omitempty"`
	EnableResourceNameDNSAaaaRecord *bool   `json:"enableResourceNameDnsAaaaRecord,omitempty"`
	HostnameType                    *string `json:"hostnameType,omitempty"`
}

// SpotInstanceRequestSpecForProviderRootBlockDevice defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.rootBlockDevice.
type SpotInstanceRequestSpecForProviderRootBlockDevice struct {
	DeleteOnTermination *bool    `json:"deleteOnTermination,omitempty"`
	Encrypted           *bool    `json:"encrypted,omitempty"`
	Iops                *float32 `json:"iops,omitempty"`

	// KmsKeyID The Spot Instance Request ID.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll    *map[string]string `json:"tagsAll,omitempty"`
	Throughput *float32           `json:"throughput,omitempty"`
	VolumeSize *float32           `json:"volumeSize,omitempty"`
	VolumeType *string            `json:"volumeType,omitempty"`
}

// SpotInstanceRequestSpecForProviderSecondaryNetworkInterfaceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.secondaryNetworkInterface.
type SpotInstanceRequestSpecForProviderSecondaryNetworkInterfaceItem struct {
	DeleteOnTermination   *bool    `json:"deleteOnTermination,omitempty"`
	DeviceIndex           *float32 `json:"deviceIndex,omitempty"`
	InterfaceType         *string  `json:"interfaceType,omitempty"`
	NetworkCardIndex      *float32 `json:"networkCardIndex,omitempty"`
	PrivateIPAddressCount *float32 `json:"privateIpAddressCount,omitempty"`

	// SecondarySubnetID The Spot Instance Request ID.
	SecondarySubnetID *string `json:"secondarySubnetId,omitempty"`
}

// SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolution string

// SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolve string

// SpotInstanceRequestSpecForProviderSubnetIDRefPolicy Policies for referencing.
type SpotInstanceRequestSpecForProviderSubnetIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SpotInstanceRequestSpecForProviderSubnetIDRefPolicyResolve `json:"resolve,omitempty"`
}

// SpotInstanceRequestSpecForProviderSubnetIDRef Reference to a Subnet in ec2 to populate subnetId.
type SpotInstanceRequestSpecForProviderSubnetIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *SpotInstanceRequestSpecForProviderSubnetIDRefPolicy `json:"policy,omitempty"`
}

// SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolution string

// SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolve string

// SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicy Policies for selection.
type SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// SpotInstanceRequestSpecForProviderSubnetIDSelector Selector for a Subnet in ec2 to populate subnetId.
type SpotInstanceRequestSpecForProviderSubnetIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *SpotInstanceRequestSpecForProviderSubnetIDSelectorPolicy `json:"policy,omitempty"`
}

// SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolution string

// SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolve string

// SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicy Policies for referencing.
type SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicyResolve `json:"resolve,omitempty"`
}

// SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItem A NamespacedReference to a named object.
type SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItem struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItemPolicy `json:"policy,omitempty"`
}

// SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolution string

// SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolve string

// SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicy Policies for selection.
type SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelector Selector for a list of SecurityGroup in ec2 to populate vpcSecurityGroupIds.
type SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelectorPolicy `json:"policy,omitempty"`
}

// SpotInstanceRequestSpecForProvider defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.forProvider.
type SpotInstanceRequestSpecForProvider struct {
	Ami                              *string                                                             `json:"ami,omitempty"`
	AssociatePublicIPAddress         *bool                                                               `json:"associatePublicIpAddress,omitempty"`
	AvailabilityZone                 *string                                                             `json:"availabilityZone,omitempty"`
	CapacityReservationSpecification *SpotInstanceRequestSpecForProviderCapacityReservationSpecification `json:"capacityReservationSpecification,omitempty"`
	CPUOptions                       *SpotInstanceRequestSpecForProviderCPUOptions                       `json:"cpuOptions,omitempty"`
	CreditSpecification              *SpotInstanceRequestSpecForProviderCreditSpecification              `json:"creditSpecification,omitempty"`
	DisableAPIStop                   *bool                                                               `json:"disableApiStop,omitempty"`
	DisableAPITermination            *bool                                                               `json:"disableApiTermination,omitempty"`
	EbsBlockDevice                   *[]SpotInstanceRequestSpecForProviderEbsBlockDeviceItem             `json:"ebsBlockDevice,omitempty"`
	EbsOptimized                     *bool                                                               `json:"ebsOptimized,omitempty"`
	EnablePrimaryIpv6                *bool                                                               `json:"enablePrimaryIpv6,omitempty"`
	EnclaveOptions                   *SpotInstanceRequestSpecForProviderEnclaveOptions                   `json:"enclaveOptions,omitempty"`
	EphemeralBlockDevice             *[]SpotInstanceRequestSpecForProviderEphemeralBlockDeviceItem       `json:"ephemeralBlockDevice,omitempty"`
	ForceDestroy                     *bool                                                               `json:"forceDestroy,omitempty"`
	GetPasswordData                  *bool                                                               `json:"getPasswordData,omitempty"`
	Hibernation                      *bool                                                               `json:"hibernation,omitempty"`

	// HostID The Spot Instance Request ID.
	HostID                            *string `json:"hostId,omitempty"`
	HostResourceGroupArn              *string `json:"hostResourceGroupArn,omitempty"`
	IamInstanceProfile                *string `json:"iamInstanceProfile,omitempty"`
	InstanceInitiatedShutdownBehavior *string `json:"instanceInitiatedShutdownBehavior,omitempty"`

	// InstanceInterruptionBehavior Indicates Spot instance behavior when it is interrupted. Valid values are terminate, stop, or hibernate. Default value is terminate.
	InstanceInterruptionBehavior *string   `json:"instanceInterruptionBehavior,omitempty"`
	InstanceType                 *string   `json:"instanceType,omitempty"`
	Ipv6AddressCount             *float32  `json:"ipv6AddressCount,omitempty"`
	Ipv6Addresses                *[]string `json:"ipv6Addresses,omitempty"`
	KeyName                      *string   `json:"keyName,omitempty"`

	// LaunchGroup A launch group is a group of spot instances that launch together and terminate together.
	// If left empty instances are launched and terminated individually.
	LaunchGroup        *string                                                   `json:"launchGroup,omitempty"`
	LaunchTemplate     *SpotInstanceRequestSpecForProviderLaunchTemplate         `json:"launchTemplate,omitempty"`
	MaintenanceOptions *SpotInstanceRequestSpecForProviderMaintenanceOptions     `json:"maintenanceOptions,omitempty"`
	MetadataOptions    *SpotInstanceRequestSpecForProviderMetadataOptions        `json:"metadataOptions,omitempty"`
	Monitoring         *bool                                                     `json:"monitoring,omitempty"`
	NetworkInterface   *[]SpotInstanceRequestSpecForProviderNetworkInterfaceItem `json:"networkInterface,omitempty"`
	PlacementGroup     *string                                                   `json:"placementGroup,omitempty"`

	// PlacementGroupID The Spot Instance Request ID.
	PlacementGroupID         *string                                                  `json:"placementGroupId,omitempty"`
	PlacementPartitionNumber *float32                                                 `json:"placementPartitionNumber,omitempty"`
	PrivateDNSNameOptions    *SpotInstanceRequestSpecForProviderPrivateDNSNameOptions `json:"privateDnsNameOptions,omitempty"`

	// PrivateIP The private IP address assigned to the instance
	PrivateIP *string `json:"privateIp,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region                    *string                                                            `json:"region,omitempty"`
	RootBlockDevice           *SpotInstanceRequestSpecForProviderRootBlockDevice                 `json:"rootBlockDevice,omitempty"`
	SecondaryNetworkInterface *[]SpotInstanceRequestSpecForProviderSecondaryNetworkInterfaceItem `json:"secondaryNetworkInterface,omitempty"`
	SecondaryPrivateIps       *[]string                                                          `json:"secondaryPrivateIps,omitempty"`
	SecurityGroups            *[]string                                                          `json:"securityGroups,omitempty"`
	SourceDestCheck           *bool                                                              `json:"sourceDestCheck,omitempty"`

	// SpotPrice The maximum price to request on the spot market.
	SpotPrice *string `json:"spotPrice,omitempty"`

	// SpotType If set to one-time, after
	// the instance is terminated, the spot request will be closed.
	SpotType *string `json:"spotType,omitempty"`

	// SubnetID The Spot Instance Request ID.
	SubnetID *string `json:"subnetId,omitempty"`

	// SubnetIDRef Reference to a Subnet in ec2 to populate subnetId.
	SubnetIDRef *SpotInstanceRequestSpecForProviderSubnetIDRef `json:"subnetIdRef,omitempty"`

	// SubnetIDSelector Selector for a Subnet in ec2 to populate subnetId.
	SubnetIDSelector *SpotInstanceRequestSpecForProviderSubnetIDSelector `json:"subnetIdSelector,omitempty"`

	// Tags Key-value map of resource tags.
	Tags                    *map[string]string `json:"tags,omitempty"`
	Tenancy                 *string            `json:"tenancy,omitempty"`
	UserData                *string            `json:"userData,omitempty"`
	UserDataBase64          *string            `json:"userDataBase64,omitempty"`
	UserDataReplaceOnChange *bool              `json:"userDataReplaceOnChange,omitempty"`

	// ValidFrom The start date and time of the request, in UTC RFC3339 format(for example, YYYY-MM-DDTHH:MM:SSZ). The default is to start fulfilling the request immediately.
	ValidFrom *string `json:"validFrom,omitempty"`

	// ValidUntil The end date and time of the request, in UTC RFC3339 format(for example, YYYY-MM-DDTHH:MM:SSZ). At this point, no new Spot instance requests are placed or enabled to fulfill the request. The default end date is 7 days from the current date.
	ValidUntil *string `json:"validUntil,omitempty"`

	// VolumeTags Key-value map of resource tags.
	VolumeTags *map[string]string `json:"volumeTags,omitempty"`

	// VpcSecurityGroupIDRefs References to SecurityGroup in ec2 to populate vpcSecurityGroupIds.
	VpcSecurityGroupIDRefs *[]SpotInstanceRequestSpecForProviderVpcSecurityGroupIDRefsItem `json:"vpcSecurityGroupIdRefs,omitempty"`

	// VpcSecurityGroupIDSelector Selector for a list of SecurityGroup in ec2 to populate vpcSecurityGroupIds.
	VpcSecurityGroupIDSelector *SpotInstanceRequestSpecForProviderVpcSecurityGroupIDSelector `json:"vpcSecurityGroupIdSelector,omitempty"`
	VpcSecurityGroupIds        *[]string                                                     `json:"vpcSecurityGroupIds,omitempty"`
	WaitForFulfillment         *bool                                                         `json:"waitForFulfillment,omitempty"`
}

// SpotInstanceRequestSpecInitProviderCapacityReservationSpecificationCapacityReservationTarget defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.capacityReservationSpecification.capacityReservationTarget.
type SpotInstanceRequestSpecInitProviderCapacityReservationSpecificationCapacityReservationTarget struct {
	// CapacityReservationID The Spot Instance Request ID.
	CapacityReservationID               *string `json:"capacityReservationId,omitempty"`
	CapacityReservationResourceGroupArn *string `json:"capacityReservationResourceGroupArn,omitempty"`
}

// SpotInstanceRequestSpecInitProviderCapacityReservationSpecification defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.capacityReservationSpecification.
type SpotInstanceRequestSpecInitProviderCapacityReservationSpecification struct {
	CapacityReservationPreference *string                                                                                       `json:"capacityReservationPreference,omitempty"`
	CapacityReservationTarget     *SpotInstanceRequestSpecInitProviderCapacityReservationSpecificationCapacityReservationTarget `json:"capacityReservationTarget,omitempty"`
}

// SpotInstanceRequestSpecInitProviderCPUOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.cpuOptions.
type SpotInstanceRequestSpecInitProviderCPUOptions struct {
	AmdSevSnp            *string  `json:"amdSevSnp,omitempty"`
	CoreCount            *float32 `json:"coreCount,omitempty"`
	NestedVirtualization *string  `json:"nestedVirtualization,omitempty"`
	ThreadsPerCore       *float32 `json:"threadsPerCore,omitempty"`
}

// SpotInstanceRequestSpecInitProviderCreditSpecification defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.creditSpecification.
type SpotInstanceRequestSpecInitProviderCreditSpecification struct {
	CPUCredits *string `json:"cpuCredits,omitempty"`
}

// SpotInstanceRequestSpecInitProviderEbsBlockDeviceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.ebsBlockDevice.
type SpotInstanceRequestSpecInitProviderEbsBlockDeviceItem struct {
	DeleteOnTermination *bool    `json:"deleteOnTermination,omitempty"`
	DeviceName          *string  `json:"deviceName,omitempty"`
	Encrypted           *bool    `json:"encrypted,omitempty"`
	Iops                *float32 `json:"iops,omitempty"`

	// KmsKeyID The Spot Instance Request ID.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`

	// SnapshotID The Spot Instance Request ID.
	SnapshotID *string `json:"snapshotId,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll    *map[string]string `json:"tagsAll,omitempty"`
	Throughput *float32           `json:"throughput,omitempty"`
	VolumeSize *float32           `json:"volumeSize,omitempty"`
	VolumeType *string            `json:"volumeType,omitempty"`
}

// SpotInstanceRequestSpecInitProviderEnclaveOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.enclaveOptions.
type SpotInstanceRequestSpecInitProviderEnclaveOptions struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// SpotInstanceRequestSpecInitProviderEphemeralBlockDeviceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.ephemeralBlockDevice.
type SpotInstanceRequestSpecInitProviderEphemeralBlockDeviceItem struct {
	DeviceName  *string `json:"deviceName,omitempty"`
	NoDevice    *bool   `json:"noDevice,omitempty"`
	VirtualName *string `json:"virtualName,omitempty"`
}

// SpotInstanceRequestSpecInitProviderLaunchTemplate defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.launchTemplate.
type SpotInstanceRequestSpecInitProviderLaunchTemplate struct {
	// ID The Spot Instance Request ID.
	ID      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

// SpotInstanceRequestSpecInitProviderMaintenanceOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.maintenanceOptions.
type SpotInstanceRequestSpecInitProviderMaintenanceOptions struct {
	AutoRecovery *string `json:"autoRecovery,omitempty"`
}

// SpotInstanceRequestSpecInitProviderMetadataOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.metadataOptions.
type SpotInstanceRequestSpecInitProviderMetadataOptions struct {
	HTTPEndpoint            *string  `json:"httpEndpoint,omitempty"`
	HTTPProtocolIpv6        *string  `json:"httpProtocolIpv6,omitempty"`
	HTTPPutResponseHopLimit *float32 `json:"httpPutResponseHopLimit,omitempty"`
	HTTPTokens              *string  `json:"httpTokens,omitempty"`

	// InstanceMetadataTags Key-value map of resource tags.
	InstanceMetadataTags *string `json:"instanceMetadataTags,omitempty"`
}

// SpotInstanceRequestSpecInitProviderNetworkInterfaceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.networkInterface.
type SpotInstanceRequestSpecInitProviderNetworkInterfaceItem struct {
	DeleteOnTermination *bool    `json:"deleteOnTermination,omitempty"`
	DeviceIndex         *float32 `json:"deviceIndex,omitempty"`

	// NetworkInterfaceID The Spot Instance Request ID.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty"`
}

// SpotInstanceRequestSpecInitProviderPrivateDNSNameOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.privateDnsNameOptions.
type SpotInstanceRequestSpecInitProviderPrivateDNSNameOptions struct {
	EnableResourceNameDNSARecord    *bool   `json:"enableResourceNameDnsARecord,omitempty"`
	EnableResourceNameDNSAaaaRecord *bool   `json:"enableResourceNameDnsAaaaRecord,omitempty"`
	HostnameType                    *string `json:"hostnameType,omitempty"`
}

// SpotInstanceRequestSpecInitProviderRootBlockDevice defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.rootBlockDevice.
type SpotInstanceRequestSpecInitProviderRootBlockDevice struct {
	DeleteOnTermination *bool    `json:"deleteOnTermination,omitempty"`
	Encrypted           *bool    `json:"encrypted,omitempty"`
	Iops                *float32 `json:"iops,omitempty"`

	// KmsKeyID The Spot Instance Request ID.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll    *map[string]string `json:"tagsAll,omitempty"`
	Throughput *float32           `json:"throughput,omitempty"`
	VolumeSize *float32           `json:"volumeSize,omitempty"`
	VolumeType *string            `json:"volumeType,omitempty"`
}

// SpotInstanceRequestSpecInitProviderSecondaryNetworkInterfaceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.spec.initProvider.secondaryNetworkInterface.
type SpotInstanceRequestSpecInitProviderSecondaryNetworkInterfaceItem struct {
	DeleteOnTermination   *bool    `json:"deleteOnTermination,omitempty"`
	DeviceIndex           *float32 `json:"deviceIndex,omitempty"`
	InterfaceType         *string  `json:"interfaceType,omitempty"`
	NetworkCardIndex      *float32 `json:"networkCardIndex,omitempty"`
	PrivateIPAddressCount *float32 `json:"privateIpAddressCount,omitempty"`

	// SecondarySubnetID The Spot Instance Request ID.
	SecondarySubnetID *string `json:"secondarySubnetId,omitempty"`
}

// SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolution string

// SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolve string

// SpotInstanceRequestSpecInitProviderSubnetIDRefPolicy Policies for referencing.
type SpotInstanceRequestSpecInitProviderSubnetIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SpotInstanceRequestSpecInitProviderSubnetIDRefPolicyResolve `json:"resolve,omitempty"`
}

// SpotInstanceRequestSpecInitProviderSubnetIDRef Reference to a Subnet in ec2 to populate subnetId.
type SpotInstanceRequestSpecInitProviderSubnetIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *SpotInstanceRequestSpecInitProviderSubnetIDRefPolicy `json:"policy,omitempty"`
}

// SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolution string

// SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolve string

// SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicy Policies for selection.
type SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// SpotInstanceRequestSpecInitProviderSubnetIDSelector Selector for a Subnet in ec2 to populate subnetId.
type SpotInstanceRequestSpecInitProviderSubnetIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *SpotInstanceRequestSpecInitProviderSubnetIDSelectorPolicy `json:"policy,omitempty"`
}

// SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolution string

// SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolve string

// SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicy Policies for referencing.
type SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicyResolve `json:"resolve,omitempty"`
}

// SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItem A NamespacedReference to a named object.
type SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItem struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItemPolicy `json:"policy,omitempty"`
}

// SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolution string

// SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolve string

// SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicy Policies for selection.
type SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelector Selector for a list of SecurityGroup in ec2 to populate vpcSecurityGroupIds.
type SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelectorPolicy `json:"policy,omitempty"`
}

// SpotInstanceRequestSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type SpotInstanceRequestSpecInitProvider struct {
	Ami                              *string                                                              `json:"ami,omitempty"`
	AssociatePublicIPAddress         *bool                                                                `json:"associatePublicIpAddress,omitempty"`
	AvailabilityZone                 *string                                                              `json:"availabilityZone,omitempty"`
	CapacityReservationSpecification *SpotInstanceRequestSpecInitProviderCapacityReservationSpecification `json:"capacityReservationSpecification,omitempty"`
	CPUOptions                       *SpotInstanceRequestSpecInitProviderCPUOptions                       `json:"cpuOptions,omitempty"`
	CreditSpecification              *SpotInstanceRequestSpecInitProviderCreditSpecification              `json:"creditSpecification,omitempty"`
	DisableAPIStop                   *bool                                                                `json:"disableApiStop,omitempty"`
	DisableAPITermination            *bool                                                                `json:"disableApiTermination,omitempty"`
	EbsBlockDevice                   *[]SpotInstanceRequestSpecInitProviderEbsBlockDeviceItem             `json:"ebsBlockDevice,omitempty"`
	EbsOptimized                     *bool                                                                `json:"ebsOptimized,omitempty"`
	EnablePrimaryIpv6                *bool                                                                `json:"enablePrimaryIpv6,omitempty"`
	EnclaveOptions                   *SpotInstanceRequestSpecInitProviderEnclaveOptions                   `json:"enclaveOptions,omitempty"`
	EphemeralBlockDevice             *[]SpotInstanceRequestSpecInitProviderEphemeralBlockDeviceItem       `json:"ephemeralBlockDevice,omitempty"`
	ForceDestroy                     *bool                                                                `json:"forceDestroy,omitempty"`
	GetPasswordData                  *bool                                                                `json:"getPasswordData,omitempty"`
	Hibernation                      *bool                                                                `json:"hibernation,omitempty"`

	// HostID The Spot Instance Request ID.
	HostID                            *string `json:"hostId,omitempty"`
	HostResourceGroupArn              *string `json:"hostResourceGroupArn,omitempty"`
	IamInstanceProfile                *string `json:"iamInstanceProfile,omitempty"`
	InstanceInitiatedShutdownBehavior *string `json:"instanceInitiatedShutdownBehavior,omitempty"`

	// InstanceInterruptionBehavior Indicates Spot instance behavior when it is interrupted. Valid values are terminate, stop, or hibernate. Default value is terminate.
	InstanceInterruptionBehavior *string   `json:"instanceInterruptionBehavior,omitempty"`
	InstanceType                 *string   `json:"instanceType,omitempty"`
	Ipv6AddressCount             *float32  `json:"ipv6AddressCount,omitempty"`
	Ipv6Addresses                *[]string `json:"ipv6Addresses,omitempty"`
	KeyName                      *string   `json:"keyName,omitempty"`

	// LaunchGroup A launch group is a group of spot instances that launch together and terminate together.
	// If left empty instances are launched and terminated individually.
	LaunchGroup        *string                                                    `json:"launchGroup,omitempty"`
	LaunchTemplate     *SpotInstanceRequestSpecInitProviderLaunchTemplate         `json:"launchTemplate,omitempty"`
	MaintenanceOptions *SpotInstanceRequestSpecInitProviderMaintenanceOptions     `json:"maintenanceOptions,omitempty"`
	MetadataOptions    *SpotInstanceRequestSpecInitProviderMetadataOptions        `json:"metadataOptions,omitempty"`
	Monitoring         *bool                                                      `json:"monitoring,omitempty"`
	NetworkInterface   *[]SpotInstanceRequestSpecInitProviderNetworkInterfaceItem `json:"networkInterface,omitempty"`
	PlacementGroup     *string                                                    `json:"placementGroup,omitempty"`

	// PlacementGroupID The Spot Instance Request ID.
	PlacementGroupID         *string                                                   `json:"placementGroupId,omitempty"`
	PlacementPartitionNumber *float32                                                  `json:"placementPartitionNumber,omitempty"`
	PrivateDNSNameOptions    *SpotInstanceRequestSpecInitProviderPrivateDNSNameOptions `json:"privateDnsNameOptions,omitempty"`

	// PrivateIP The private IP address assigned to the instance
	PrivateIP                 *string                                                             `json:"privateIp,omitempty"`
	RootBlockDevice           *SpotInstanceRequestSpecInitProviderRootBlockDevice                 `json:"rootBlockDevice,omitempty"`
	SecondaryNetworkInterface *[]SpotInstanceRequestSpecInitProviderSecondaryNetworkInterfaceItem `json:"secondaryNetworkInterface,omitempty"`
	SecondaryPrivateIps       *[]string                                                           `json:"secondaryPrivateIps,omitempty"`
	SecurityGroups            *[]string                                                           `json:"securityGroups,omitempty"`
	SourceDestCheck           *bool                                                               `json:"sourceDestCheck,omitempty"`

	// SpotPrice The maximum price to request on the spot market.
	SpotPrice *string `json:"spotPrice,omitempty"`

	// SpotType If set to one-time, after
	// the instance is terminated, the spot request will be closed.
	SpotType *string `json:"spotType,omitempty"`

	// SubnetID The Spot Instance Request ID.
	SubnetID *string `json:"subnetId,omitempty"`

	// SubnetIDRef Reference to a Subnet in ec2 to populate subnetId.
	SubnetIDRef *SpotInstanceRequestSpecInitProviderSubnetIDRef `json:"subnetIdRef,omitempty"`

	// SubnetIDSelector Selector for a Subnet in ec2 to populate subnetId.
	SubnetIDSelector *SpotInstanceRequestSpecInitProviderSubnetIDSelector `json:"subnetIdSelector,omitempty"`

	// Tags Key-value map of resource tags.
	Tags                    *map[string]string `json:"tags,omitempty"`
	Tenancy                 *string            `json:"tenancy,omitempty"`
	UserData                *string            `json:"userData,omitempty"`
	UserDataBase64          *string            `json:"userDataBase64,omitempty"`
	UserDataReplaceOnChange *bool              `json:"userDataReplaceOnChange,omitempty"`

	// ValidFrom The start date and time of the request, in UTC RFC3339 format(for example, YYYY-MM-DDTHH:MM:SSZ). The default is to start fulfilling the request immediately.
	ValidFrom *string `json:"validFrom,omitempty"`

	// ValidUntil The end date and time of the request, in UTC RFC3339 format(for example, YYYY-MM-DDTHH:MM:SSZ). At this point, no new Spot instance requests are placed or enabled to fulfill the request. The default end date is 7 days from the current date.
	ValidUntil *string `json:"validUntil,omitempty"`

	// VolumeTags Key-value map of resource tags.
	VolumeTags *map[string]string `json:"volumeTags,omitempty"`

	// VpcSecurityGroupIDRefs References to SecurityGroup in ec2 to populate vpcSecurityGroupIds.
	VpcSecurityGroupIDRefs *[]SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDRefsItem `json:"vpcSecurityGroupIdRefs,omitempty"`

	// VpcSecurityGroupIDSelector Selector for a list of SecurityGroup in ec2 to populate vpcSecurityGroupIds.
	VpcSecurityGroupIDSelector *SpotInstanceRequestSpecInitProviderVpcSecurityGroupIDSelector `json:"vpcSecurityGroupIdSelector,omitempty"`
	VpcSecurityGroupIds        *[]string                                                      `json:"vpcSecurityGroupIds,omitempty"`
	WaitForFulfillment         *bool                                                          `json:"waitForFulfillment,omitempty"`
}

// SpotInstanceRequestSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type SpotInstanceRequestSpecManagementPoliciesItem string

// SpotInstanceRequestSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type SpotInstanceRequestSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// SpotInstanceRequestSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type SpotInstanceRequestSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// SpotInstanceRequestSpec SpotInstanceRequestSpec defines the desired state of SpotInstanceRequest
type SpotInstanceRequestSpec struct {
	ForProvider *SpotInstanceRequestSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *SpotInstanceRequestSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]SpotInstanceRequestSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *SpotInstanceRequestSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *SpotInstanceRequestSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// SpotInstanceRequestStatusAtProviderCapacityReservationSpecificationCapacityReservationTarget defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.capacityReservationSpecification.capacityReservationTarget.
type SpotInstanceRequestStatusAtProviderCapacityReservationSpecificationCapacityReservationTarget struct {
	// CapacityReservationID The Spot Instance Request ID.
	CapacityReservationID               *string `json:"capacityReservationId,omitempty"`
	CapacityReservationResourceGroupArn *string `json:"capacityReservationResourceGroupArn,omitempty"`
}

// SpotInstanceRequestStatusAtProviderCapacityReservationSpecification defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.capacityReservationSpecification.
type SpotInstanceRequestStatusAtProviderCapacityReservationSpecification struct {
	CapacityReservationPreference *string                                                                                       `json:"capacityReservationPreference,omitempty"`
	CapacityReservationTarget     *SpotInstanceRequestStatusAtProviderCapacityReservationSpecificationCapacityReservationTarget `json:"capacityReservationTarget,omitempty"`
}

// SpotInstanceRequestStatusAtProviderCPUOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.cpuOptions.
type SpotInstanceRequestStatusAtProviderCPUOptions struct {
	AmdSevSnp            *string  `json:"amdSevSnp,omitempty"`
	CoreCount            *float32 `json:"coreCount,omitempty"`
	NestedVirtualization *string  `json:"nestedVirtualization,omitempty"`
	ThreadsPerCore       *float32 `json:"threadsPerCore,omitempty"`
}

// SpotInstanceRequestStatusAtProviderCreditSpecification defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.creditSpecification.
type SpotInstanceRequestStatusAtProviderCreditSpecification struct {
	CPUCredits *string `json:"cpuCredits,omitempty"`
}

// SpotInstanceRequestStatusAtProviderEbsBlockDeviceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.ebsBlockDevice.
type SpotInstanceRequestStatusAtProviderEbsBlockDeviceItem struct {
	DeleteOnTermination *bool    `json:"deleteOnTermination,omitempty"`
	DeviceName          *string  `json:"deviceName,omitempty"`
	Encrypted           *bool    `json:"encrypted,omitempty"`
	Iops                *float32 `json:"iops,omitempty"`

	// KmsKeyID The Spot Instance Request ID.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`

	// SnapshotID The Spot Instance Request ID.
	SnapshotID *string `json:"snapshotId,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll    *map[string]string `json:"tagsAll,omitempty"`
	Throughput *float32           `json:"throughput,omitempty"`

	// VolumeID The Spot Instance Request ID.
	VolumeID   *string  `json:"volumeId,omitempty"`
	VolumeSize *float32 `json:"volumeSize,omitempty"`
	VolumeType *string  `json:"volumeType,omitempty"`
}

// SpotInstanceRequestStatusAtProviderEnclaveOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.enclaveOptions.
type SpotInstanceRequestStatusAtProviderEnclaveOptions struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// SpotInstanceRequestStatusAtProviderEphemeralBlockDeviceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.ephemeralBlockDevice.
type SpotInstanceRequestStatusAtProviderEphemeralBlockDeviceItem struct {
	DeviceName  *string `json:"deviceName,omitempty"`
	NoDevice    *bool   `json:"noDevice,omitempty"`
	VirtualName *string `json:"virtualName,omitempty"`
}

// SpotInstanceRequestStatusAtProviderLaunchTemplate defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.launchTemplate.
type SpotInstanceRequestStatusAtProviderLaunchTemplate struct {
	// ID The Spot Instance Request ID.
	ID      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

// SpotInstanceRequestStatusAtProviderMaintenanceOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.maintenanceOptions.
type SpotInstanceRequestStatusAtProviderMaintenanceOptions struct {
	AutoRecovery *string `json:"autoRecovery,omitempty"`
}

// SpotInstanceRequestStatusAtProviderMetadataOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.metadataOptions.
type SpotInstanceRequestStatusAtProviderMetadataOptions struct {
	HTTPEndpoint            *string  `json:"httpEndpoint,omitempty"`
	HTTPProtocolIpv6        *string  `json:"httpProtocolIpv6,omitempty"`
	HTTPPutResponseHopLimit *float32 `json:"httpPutResponseHopLimit,omitempty"`
	HTTPTokens              *string  `json:"httpTokens,omitempty"`

	// InstanceMetadataTags Key-value map of resource tags.
	InstanceMetadataTags *string `json:"instanceMetadataTags,omitempty"`
}

// SpotInstanceRequestStatusAtProviderNetworkInterfaceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.networkInterface.
type SpotInstanceRequestStatusAtProviderNetworkInterfaceItem struct {
	DeleteOnTermination *bool    `json:"deleteOnTermination,omitempty"`
	DeviceIndex         *float32 `json:"deviceIndex,omitempty"`
	NetworkCardIndex    *float32 `json:"networkCardIndex,omitempty"`

	// NetworkInterfaceID The Spot Instance Request ID.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty"`
}

// SpotInstanceRequestStatusAtProviderPrimaryNetworkInterfaceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.primaryNetworkInterface.
type SpotInstanceRequestStatusAtProviderPrimaryNetworkInterfaceItem struct {
	DeleteOnTermination *bool `json:"deleteOnTermination,omitempty"`

	// NetworkInterfaceID The Spot Instance Request ID.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty"`
}

// SpotInstanceRequestStatusAtProviderPrivateDNSNameOptions defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.privateDnsNameOptions.
type SpotInstanceRequestStatusAtProviderPrivateDNSNameOptions struct {
	EnableResourceNameDNSARecord    *bool   `json:"enableResourceNameDnsARecord,omitempty"`
	EnableResourceNameDNSAaaaRecord *bool   `json:"enableResourceNameDnsAaaaRecord,omitempty"`
	HostnameType                    *string `json:"hostnameType,omitempty"`
}

// SpotInstanceRequestStatusAtProviderRootBlockDevice defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.rootBlockDevice.
type SpotInstanceRequestStatusAtProviderRootBlockDevice struct {
	DeleteOnTermination *bool    `json:"deleteOnTermination,omitempty"`
	DeviceName          *string  `json:"deviceName,omitempty"`
	Encrypted           *bool    `json:"encrypted,omitempty"`
	Iops                *float32 `json:"iops,omitempty"`

	// KmsKeyID The Spot Instance Request ID.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll    *map[string]string `json:"tagsAll,omitempty"`
	Throughput *float32           `json:"throughput,omitempty"`

	// VolumeID The Spot Instance Request ID.
	VolumeID   *string  `json:"volumeId,omitempty"`
	VolumeSize *float32 `json:"volumeSize,omitempty"`
	VolumeType *string  `json:"volumeType,omitempty"`
}

// SpotInstanceRequestStatusAtProviderSecondaryNetworkInterfaceItem defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.secondaryNetworkInterface.
type SpotInstanceRequestStatusAtProviderSecondaryNetworkInterfaceItem struct {
	DeleteOnTermination   *bool     `json:"deleteOnTermination,omitempty"`
	DeviceIndex           *float32  `json:"deviceIndex,omitempty"`
	InterfaceType         *string   `json:"interfaceType,omitempty"`
	MacAddress            *string   `json:"macAddress,omitempty"`
	NetworkCardIndex      *float32  `json:"networkCardIndex,omitempty"`
	PrivateIPAddressCount *float32  `json:"privateIpAddressCount,omitempty"`
	PrivateIPAddresses    *[]string `json:"privateIpAddresses,omitempty"`

	// SecondaryInterfaceID The Spot Instance Request ID.
	SecondaryInterfaceID *string `json:"secondaryInterfaceId,omitempty"`

	// SecondaryNetworkID The Spot Instance Request ID.
	SecondaryNetworkID *string `json:"secondaryNetworkId,omitempty"`

	// SecondarySubnetID The Spot Instance Request ID.
	SecondarySubnetID *string `json:"secondarySubnetId,omitempty"`
	SourceDestCheck   *bool   `json:"sourceDestCheck,omitempty"`
	Status            *string `json:"status,omitempty"`
}

// SpotInstanceRequestStatusAtProvider defines model for io.upbound.m.aws.ec2.v1beta1.SpotInstanceRequest.status.atProvider.
type SpotInstanceRequestStatusAtProvider struct {
	Ami                              *string                                                              `json:"ami,omitempty"`
	Arn                              *string                                                              `json:"arn,omitempty"`
	AssociatePublicIPAddress         *bool                                                                `json:"associatePublicIpAddress,omitempty"`
	AvailabilityZone                 *string                                                              `json:"availabilityZone,omitempty"`
	CapacityReservationSpecification *SpotInstanceRequestStatusAtProviderCapacityReservationSpecification `json:"capacityReservationSpecification,omitempty"`
	CPUOptions                       *SpotInstanceRequestStatusAtProviderCPUOptions                       `json:"cpuOptions,omitempty"`
	CreditSpecification              *SpotInstanceRequestStatusAtProviderCreditSpecification              `json:"creditSpecification,omitempty"`
	DisableAPIStop                   *bool                                                                `json:"disableApiStop,omitempty"`
	DisableAPITermination            *bool                                                                `json:"disableApiTermination,omitempty"`
	EbsBlockDevice                   *[]SpotInstanceRequestStatusAtProviderEbsBlockDeviceItem             `json:"ebsBlockDevice,omitempty"`
	EbsOptimized                     *bool                                                                `json:"ebsOptimized,omitempty"`
	EnablePrimaryIpv6                *bool                                                                `json:"enablePrimaryIpv6,omitempty"`
	EnclaveOptions                   *SpotInstanceRequestStatusAtProviderEnclaveOptions                   `json:"enclaveOptions,omitempty"`
	EphemeralBlockDevice             *[]SpotInstanceRequestStatusAtProviderEphemeralBlockDeviceItem       `json:"ephemeralBlockDevice,omitempty"`
	ForceDestroy                     *bool                                                                `json:"forceDestroy,omitempty"`
	GetPasswordData                  *bool                                                                `json:"getPasswordData,omitempty"`
	Hibernation                      *bool                                                                `json:"hibernation,omitempty"`

	// HostID The Spot Instance Request ID.
	HostID               *string `json:"hostId,omitempty"`
	HostResourceGroupArn *string `json:"hostResourceGroupArn,omitempty"`
	IamInstanceProfile   *string `json:"iamInstanceProfile,omitempty"`

	// ID The Spot Instance Request ID.
	ID                                *string `json:"id,omitempty"`
	InstanceInitiatedShutdownBehavior *string `json:"instanceInitiatedShutdownBehavior,omitempty"`

	// InstanceInterruptionBehavior Indicates Spot instance behavior when it is interrupted. Valid values are terminate, stop, or hibernate. Default value is terminate.
	InstanceInterruptionBehavior *string   `json:"instanceInterruptionBehavior,omitempty"`
	InstanceState                *string   `json:"instanceState,omitempty"`
	InstanceType                 *string   `json:"instanceType,omitempty"`
	Ipv6AddressCount             *float32  `json:"ipv6AddressCount,omitempty"`
	Ipv6Addresses                *[]string `json:"ipv6Addresses,omitempty"`
	KeyName                      *string   `json:"keyName,omitempty"`

	// LaunchGroup A launch group is a group of spot instances that launch together and terminate together.
	// If left empty instances are launched and terminated individually.
	LaunchGroup        *string                                                    `json:"launchGroup,omitempty"`
	LaunchTemplate     *SpotInstanceRequestStatusAtProviderLaunchTemplate         `json:"launchTemplate,omitempty"`
	MaintenanceOptions *SpotInstanceRequestStatusAtProviderMaintenanceOptions     `json:"maintenanceOptions,omitempty"`
	MetadataOptions    *SpotInstanceRequestStatusAtProviderMetadataOptions        `json:"metadataOptions,omitempty"`
	Monitoring         *bool                                                      `json:"monitoring,omitempty"`
	NetworkInterface   *[]SpotInstanceRequestStatusAtProviderNetworkInterfaceItem `json:"networkInterface,omitempty"`
	OutpostArn         *string                                                    `json:"outpostArn,omitempty"`
	PasswordData       *string                                                    `json:"passwordData,omitempty"`
	PlacementGroup     *string                                                    `json:"placementGroup,omitempty"`

	// PlacementGroupID The Spot Instance Request ID.
	PlacementGroupID         *string                                                           `json:"placementGroupId,omitempty"`
	PlacementPartitionNumber *float32                                                          `json:"placementPartitionNumber,omitempty"`
	PrimaryNetworkInterface  *[]SpotInstanceRequestStatusAtProviderPrimaryNetworkInterfaceItem `json:"primaryNetworkInterface,omitempty"`

	// PrimaryNetworkInterfaceID The Spot Instance Request ID.
	PrimaryNetworkInterfaceID *string `json:"primaryNetworkInterfaceId,omitempty"`

	// PrivateDNS The private DNS name assigned to the instance. Can only be
	// used inside the Amazon EC2, and only available if you've enabled DNS hostnames
	// for your VPC
	PrivateDNS            *string                                                   `json:"privateDns,omitempty"`
	PrivateDNSNameOptions *SpotInstanceRequestStatusAtProviderPrivateDNSNameOptions `json:"privateDnsNameOptions,omitempty"`

	// PrivateIP The private IP address assigned to the instance
	PrivateIP *string `json:"privateIp,omitempty"`

	// PublicDNS The public DNS name assigned to the instance. For EC2-VPC, this
	// is only available if you've enabled DNS hostnames for your VPC
	PublicDNS *string `json:"publicDns,omitempty"`

	// PublicIP The public IP address assigned to the instance, if applicable.
	PublicIP *string `json:"publicIp,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region                    *string                                                             `json:"region,omitempty"`
	RootBlockDevice           *SpotInstanceRequestStatusAtProviderRootBlockDevice                 `json:"rootBlockDevice,omitempty"`
	SecondaryNetworkInterface *[]SpotInstanceRequestStatusAtProviderSecondaryNetworkInterfaceItem `json:"secondaryNetworkInterface,omitempty"`
	SecondaryPrivateIps       *[]string                                                           `json:"secondaryPrivateIps,omitempty"`
	SecurityGroups            *[]string                                                           `json:"securityGroups,omitempty"`
	SourceDestCheck           *bool                                                               `json:"sourceDestCheck,omitempty"`

	// SpotBidStatus The current bid
	// status
	// of the Spot Instance Request.
	SpotBidStatus *string `json:"spotBidStatus,omitempty"`

	// SpotInstanceID The Instance ID (if any) that is currently fulfilling
	// the Spot Instance request.
	SpotInstanceID *string `json:"spotInstanceId,omitempty"`

	// SpotPrice The maximum price to request on the spot market.
	SpotPrice *string `json:"spotPrice,omitempty"`

	// SpotRequestState The current request
	// state
	// of the Spot Instance Request.
	SpotRequestState *string `json:"spotRequestState,omitempty"`

	// SpotType If set to one-time, after
	// the instance is terminated, the spot request will be closed.
	SpotType *string `json:"spotType,omitempty"`

	// SubnetID The Spot Instance Request ID.
	SubnetID *string `json:"subnetId,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll                 *map[string]string `json:"tagsAll,omitempty"`
	Tenancy                 *string            `json:"tenancy,omitempty"`
	UserData                *string            `json:"userData,omitempty"`
	UserDataBase64          *string            `json:"userDataBase64,omitempty"`
	UserDataReplaceOnChange *bool              `json:"userDataReplaceOnChange,omitempty"`

	// ValidFrom The start date and time of the request, in UTC RFC3339 format(for example, YYYY-MM-DDTHH:MM:SSZ). The default is to start fulfilling the request immediately.
	ValidFrom *string `json:"validFrom,omitempty"`

	// ValidUntil The end date and time of the request, in UTC RFC3339 format(for example, YYYY-MM-DDTHH:MM:SSZ). At this point, no new Spot instance requests are placed or enabled to fulfill the request. The default end date is 7 days from the current date.
	ValidUntil *string `json:"validUntil,omitempty"`

	// VolumeTags Key-value map of resource tags.
	VolumeTags          *map[string]string `json:"volumeTags,omitempty"`
	VpcSecurityGroupIds *[]string          `json:"vpcSecurityGroupIds,omitempty"`
	WaitForFulfillment  *bool              `json:"waitForFulfillment,omitempty"`
}

// SpotInstanceRequestStatusConditionsItem A Condition that may apply to a resource.
type SpotInstanceRequestStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// SpotInstanceRequestStatus SpotInstanceRequestStatus defines the observed state of SpotInstanceRequest.
type SpotInstanceRequestStatus struct {
	AtProvider *SpotInstanceRequestStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]SpotInstanceRequestStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// SpotInstanceRequest SpotInstanceRequest is the Schema for the SpotInstanceRequests API. Provides a Spot Instance Request resource.
type SpotInstanceRequest struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *SpotInstanceRequestAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *SpotInstanceRequestKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec SpotInstanceRequestSpec defines the desired state of SpotInstanceRequest
	Spec *SpotInstanceRequestSpec `json:"spec,omitempty"`

	// Status SpotInstanceRequestStatus defines the observed state of SpotInstanceRequest.
	Status *SpotInstanceRequestStatus `json:"status,omitempty"`
}

// IoUpboundMAwsEc2V1Beta1SpotInstanceRequestList SpotInstanceRequestList is a list of SpotInstanceRequest
type IoUpboundMAwsEc2V1Beta1SpotInstanceRequestList = SpotInstanceRequestList

// SpotInstanceRequestList SpotInstanceRequestList is a list of SpotInstanceRequest
type SpotInstanceRequestList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of spotinstancerequests. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundMAwsEc2V1Beta1SpotInstanceRequest `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
