// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for LockAPIVersion.
const (
	LockAPIVersionPkgCrossplaneIoV1Beta1 LockAPIVersion = "pkg.crossplane.io/v1beta1"
)

// Valid indicates whether the value is a known member of the LockAPIVersion enum.
func (e LockAPIVersion) Valid() bool {
	switch e {
	case LockAPIVersionPkgCrossplaneIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for LockKind.
const (
	LockKindLock LockKind = "Lock"
)

// Valid indicates whether the value is a known member of the LockKind enum.
func (e LockKind) Valid() bool {
	switch e {
	case LockKindLock:
		return true
	default:
		return false
	}
}

// Defines values for LockPackagesItemDependenciesItemType.
const (
	LockPackagesItemDependenciesItemTypeConfiguration LockPackagesItemDependenciesItemType = "Configuration"
	LockPackagesItemDependenciesItemTypeFunction      LockPackagesItemDependenciesItemType = "Function"
	LockPackagesItemDependenciesItemTypeProvider      LockPackagesItemDependenciesItemType = "Provider"
)

// Valid indicates whether the value is a known member of the LockPackagesItemDependenciesItemType enum.
func (e LockPackagesItemDependenciesItemType) Valid() bool {
	switch e {
	case LockPackagesItemDependenciesItemTypeConfiguration:
		return true
	case LockPackagesItemDependenciesItemTypeFunction:
		return true
	case LockPackagesItemDependenciesItemTypeProvider:
		return true
	default:
		return false
	}
}

// Defines values for LockPackagesItemType.
const (
	LockPackagesItemTypeConfiguration LockPackagesItemType = "Configuration"
	LockPackagesItemTypeFunction      LockPackagesItemType = "Function"
	LockPackagesItemTypeProvider      LockPackagesItemType = "Provider"
)

// Valid indicates whether the value is a known member of the LockPackagesItemType enum.
func (e LockPackagesItemType) Valid() bool {
	switch e {
	case LockPackagesItemTypeConfiguration:
		return true
	case LockPackagesItemTypeFunction:
		return true
	case LockPackagesItemTypeProvider:
		return true
	default:
		return false
	}
}

// IoCrossplanePkgV1Beta1Lock Lock is the CRD type that tracks package dependencies.
type IoCrossplanePkgV1Beta1Lock = Lock

// LockAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type LockAPIVersion string

// LockKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type LockKind string

// LockPackagesItemDependenciesItemType Type is the type of package. Can be either Configuration or Provider.
//
// Deprecated: Specify an apiVersion and kind instead.
type LockPackagesItemDependenciesItemType string

// LockPackagesItemDependenciesItem A Dependency is a dependency of a package in the lock.
type LockPackagesItemDependenciesItem struct {
	// APIVersion APIVersion of the package.
	APIVersion *string `json:"apiVersion,omitempty"`

	// Constraints Constraints is a valid semver range or a digest, which will be used to select a valid
	// dependency version.
	Constraints *string `json:"constraints,omitempty"`

	// Kind Kind of the package (not the kind of the package revision).
	Kind *string `json:"kind,omitempty"`

	// Package Package is the OCI image name without a tag or digest.
	Package *string `json:"package,omitempty"`

	// Type Type is the type of package. Can be either Configuration or Provider.
	//
	// Deprecated: Specify an apiVersion and kind instead.
	Type *LockPackagesItemDependenciesItemType `json:"type,omitempty"`
}

// LockPackagesItemType Type is the type of package.
//
// Deprecated: Specify an apiVersion and kind instead.
type LockPackagesItemType string

// LockPackagesItem LockPackage is a package that is in the lock.
type LockPackagesItem struct {
	// APIVersion APIVersion of the package.
	APIVersion *string `json:"apiVersion,omitempty"`

	// Dependencies Dependencies are the list of dependencies of this package. The order of
	// the dependencies will dictate the order in which they are resolved.
	Dependencies *[]LockPackagesItemDependenciesItem `json:"dependencies,omitempty"`

	// Kind Kind of the package (not the kind of the package revision).
	Kind *string `json:"kind,omitempty"`

	// Name Name corresponds to the name of the package revision for this package.
	Name *string `json:"name,omitempty"`

	// Source Source is the OCI image name without a tag or digest.
	Source *string `json:"source,omitempty"`

	// Type Type is the type of package.
	//
	// Deprecated: Specify an apiVersion and kind instead.
	Type *LockPackagesItemType `json:"type,omitempty"`

	// Version Version is the tag or digest of the OCI image.
	Version *string `json:"version,omitempty"`
}

// LockStatusConditionsItem A Condition that may apply to a resource.
type LockStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// LockStatus Status of the Lock.
type LockStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]LockStatusConditionsItem `json:"conditions,omitempty"`
}

// Lock Lock is the CRD type that tracks package dependencies.
type Lock struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *LockAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *LockKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta  `json:"metadata,omitempty"`
	Packages *[]LockPackagesItem `json:"packages,omitempty"`

	// Status Status of the Lock.
	Status *LockStatus `json:"status,omitempty"`
}

// IoCrossplanePkgV1Beta1LockList LockList is a list of Lock
type IoCrossplanePkgV1Beta1LockList = LockList

// LockList LockList is a list of Lock
type LockList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of locks. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplanePkgV1Beta1Lock `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
