// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BackendBucketSignedURLKeyAPIVersion.
const (
	BackendBucketSignedURLKeyAPIVersionComputeGcpUpboundIoV1Beta1 BackendBucketSignedURLKeyAPIVersion = "compute.gcp.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeyAPIVersion enum.
func (e BackendBucketSignedURLKeyAPIVersion) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeyAPIVersionComputeGcpUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeyKind.
const (
	BackendBucketSignedURLKeyKindBackendBucketSignedURLKey BackendBucketSignedURLKeyKind = "BackendBucketSignedURLKey"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeyKind enum.
func (e BackendBucketSignedURLKeyKind) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeyKindBackendBucketSignedURLKey:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecDeletionPolicy.
const (
	BackendBucketSignedURLKeySpecDeletionPolicyDelete BackendBucketSignedURLKeySpecDeletionPolicy = "Delete"
	BackendBucketSignedURLKeySpecDeletionPolicyOrphan BackendBucketSignedURLKeySpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecDeletionPolicy enum.
func (e BackendBucketSignedURLKeySpecDeletionPolicy) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecDeletionPolicyDelete:
		return true
	case BackendBucketSignedURLKeySpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolution.
const (
	BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolutionOptional BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolution = "Optional"
	BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolutionRequired BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolution enum.
func (e BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolutionOptional:
		return true
	case BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolve.
const (
	BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolveAlways       BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolve = "Always"
	BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolveIfNotPresent BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolve enum.
func (e BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolveAlways:
		return true
	case BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolution.
const (
	BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolutionOptional BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolution = "Optional"
	BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolutionRequired BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolution enum.
func (e BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolutionOptional:
		return true
	case BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolve.
const (
	BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolveAlways       BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolve = "Always"
	BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolveIfNotPresent BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolve enum.
func (e BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolveAlways:
		return true
	case BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolution.
const (
	BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolutionOptional BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolution = "Optional"
	BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolutionRequired BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolution enum.
func (e BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolutionOptional:
		return true
	case BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolve.
const (
	BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolveAlways       BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolve = "Always"
	BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolveIfNotPresent BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolve enum.
func (e BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolveAlways:
		return true
	case BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolution.
const (
	BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolutionOptional BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolution = "Optional"
	BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolutionRequired BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolution enum.
func (e BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolutionOptional:
		return true
	case BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolve.
const (
	BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolveAlways       BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolve = "Always"
	BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolveIfNotPresent BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolve enum.
func (e BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolveAlways:
		return true
	case BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecManagementPoliciesItem.
const (
	BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItem               BackendBucketSignedURLKeySpecManagementPoliciesItem = "*"
	BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemCreate         BackendBucketSignedURLKeySpecManagementPoliciesItem = "Create"
	BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemDelete         BackendBucketSignedURLKeySpecManagementPoliciesItem = "Delete"
	BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemLateInitialize BackendBucketSignedURLKeySpecManagementPoliciesItem = "LateInitialize"
	BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemObserve        BackendBucketSignedURLKeySpecManagementPoliciesItem = "Observe"
	BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemUpdate         BackendBucketSignedURLKeySpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecManagementPoliciesItem enum.
func (e BackendBucketSignedURLKeySpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItem:
		return true
	case BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemCreate:
		return true
	case BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemDelete:
		return true
	case BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemLateInitialize:
		return true
	case BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemObserve:
		return true
	case BackendBucketSignedURLKeySpecManagementPoliciesItemBackendBucketSignedURLKeySpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolution.
const (
	BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolutionOptional BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolution = "Optional"
	BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolutionRequired BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolution enum.
func (e BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolutionOptional:
		return true
	case BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolve.
const (
	BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolveAlways       BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolve = "Always"
	BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolveIfNotPresent BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolve enum.
func (e BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolveAlways:
		return true
	case BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoUpboundGcpComputeV1Beta1BackendBucketSignedURLKey BackendBucketSignedURLKey is the Schema for the BackendBucketSignedURLKeys API. A key for signing Cloud CDN signed URLs for BackendBuckets.
type IoUpboundGcpComputeV1Beta1BackendBucketSignedURLKey = BackendBucketSignedURLKey

// BackendBucketSignedURLKeyAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BackendBucketSignedURLKeyAPIVersion string

// BackendBucketSignedURLKeyKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BackendBucketSignedURLKeyKind string

// BackendBucketSignedURLKeySpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type BackendBucketSignedURLKeySpecDeletionPolicy string

// BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolution string

// BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolve string

// BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicy Policies for referencing.
type BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BackendBucketSignedURLKeySpecForProviderBackendBucketRef Reference to a BackendBucket in compute to populate backendBucket.
type BackendBucketSignedURLKeySpecForProviderBackendBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BackendBucketSignedURLKeySpecForProviderBackendBucketRefPolicy `json:"policy,omitempty"`
}

// BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolution string

// BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolve string

// BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicy Policies for selection.
type BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BackendBucketSignedURLKeySpecForProviderBackendBucketSelector Selector for a BackendBucket in compute to populate backendBucket.
type BackendBucketSignedURLKeySpecForProviderBackendBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BackendBucketSignedURLKeySpecForProviderBackendBucketSelectorPolicy `json:"policy,omitempty"`
}

// BackendBucketSignedURLKeySpecForProviderKeyValueSecretRef 128-bit key value used for signing the URL. The key value must be a
// valid RFC 4648 Section 5 base64url encoded string.
// Note: This property is sensitive and will not be displayed in the plan.
type BackendBucketSignedURLKeySpecForProviderKeyValueSecretRef struct {
	// Key The key to select.
	Key *string `json:"key,omitempty"`

	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// BackendBucketSignedURLKeySpecForProvider defines model for io.upbound.gcp.compute.v1beta1.BackendBucketSignedURLKey.spec.forProvider.
type BackendBucketSignedURLKeySpecForProvider struct {
	// BackendBucket The backend bucket this signed URL key belongs.
	BackendBucket *string `json:"backendBucket,omitempty"`

	// BackendBucketRef Reference to a BackendBucket in compute to populate backendBucket.
	BackendBucketRef *BackendBucketSignedURLKeySpecForProviderBackendBucketRef `json:"backendBucketRef,omitempty"`

	// BackendBucketSelector Selector for a BackendBucket in compute to populate backendBucket.
	BackendBucketSelector *BackendBucketSignedURLKeySpecForProviderBackendBucketSelector `json:"backendBucketSelector,omitempty"`

	// KeyValueSecretRef 128-bit key value used for signing the URL. The key value must be a
	// valid RFC 4648 Section 5 base64url encoded string.
	// Note: This property is sensitive and will not be displayed in the plan.
	KeyValueSecretRef *BackendBucketSignedURLKeySpecForProviderKeyValueSecretRef `json:"keyValueSecretRef,omitempty"`

	// Name Name of the signed URL key.
	Name *string `json:"name,omitempty"`

	// Project The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty"`
}

// BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolution string

// BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolve string

// BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicy Policies for referencing.
type BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BackendBucketSignedURLKeySpecInitProviderBackendBucketRef Reference to a BackendBucket in compute to populate backendBucket.
type BackendBucketSignedURLKeySpecInitProviderBackendBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BackendBucketSignedURLKeySpecInitProviderBackendBucketRefPolicy `json:"policy,omitempty"`
}

// BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolution string

// BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolve string

// BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicy Policies for selection.
type BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BackendBucketSignedURLKeySpecInitProviderBackendBucketSelector Selector for a BackendBucket in compute to populate backendBucket.
type BackendBucketSignedURLKeySpecInitProviderBackendBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BackendBucketSignedURLKeySpecInitProviderBackendBucketSelectorPolicy `json:"policy,omitempty"`
}

// BackendBucketSignedURLKeySpecInitProviderKeyValueSecretRef 128-bit key value used for signing the URL. The key value must be a
// valid RFC 4648 Section 5 base64url encoded string.
// Note: This property is sensitive and will not be displayed in the plan.
type BackendBucketSignedURLKeySpecInitProviderKeyValueSecretRef struct {
	// Key The key to select.
	Key *string `json:"key,omitempty"`

	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// BackendBucketSignedURLKeySpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BackendBucketSignedURLKeySpecInitProvider struct {
	// BackendBucket The backend bucket this signed URL key belongs.
	BackendBucket *string `json:"backendBucket,omitempty"`

	// BackendBucketRef Reference to a BackendBucket in compute to populate backendBucket.
	BackendBucketRef *BackendBucketSignedURLKeySpecInitProviderBackendBucketRef `json:"backendBucketRef,omitempty"`

	// BackendBucketSelector Selector for a BackendBucket in compute to populate backendBucket.
	BackendBucketSelector *BackendBucketSignedURLKeySpecInitProviderBackendBucketSelector `json:"backendBucketSelector,omitempty"`

	// KeyValueSecretRef 128-bit key value used for signing the URL. The key value must be a
	// valid RFC 4648 Section 5 base64url encoded string.
	// Note: This property is sensitive and will not be displayed in the plan.
	KeyValueSecretRef *BackendBucketSignedURLKeySpecInitProviderKeyValueSecretRef `json:"keyValueSecretRef,omitempty"`

	// Name Name of the signed URL key.
	Name *string `json:"name,omitempty"`

	// Project The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty"`
}

// BackendBucketSignedURLKeySpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BackendBucketSignedURLKeySpecManagementPoliciesItem string

// BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolution string

// BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolve string

// BackendBucketSignedURLKeySpecProviderConfigRefPolicy Policies for referencing.
type BackendBucketSignedURLKeySpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BackendBucketSignedURLKeySpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// BackendBucketSignedURLKeySpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BackendBucketSignedURLKeySpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BackendBucketSignedURLKeySpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// BackendBucketSignedURLKeySpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BackendBucketSignedURLKeySpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// BackendBucketSignedURLKeySpec BackendBucketSignedURLKeySpec defines the desired state of BackendBucketSignedURLKey
type BackendBucketSignedURLKeySpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *BackendBucketSignedURLKeySpecDeletionPolicy `json:"deletionPolicy,omitempty"`
	ForProvider    *BackendBucketSignedURLKeySpecForProvider    `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BackendBucketSignedURLKeySpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BackendBucketSignedURLKeySpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BackendBucketSignedURLKeySpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BackendBucketSignedURLKeySpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BackendBucketSignedURLKeyStatusAtProvider defines model for io.upbound.gcp.compute.v1beta1.BackendBucketSignedURLKey.status.atProvider.
type BackendBucketSignedURLKeyStatusAtProvider struct {
	// BackendBucket The backend bucket this signed URL key belongs.
	BackendBucket *string `json:"backendBucket,omitempty"`

	// ID an identifier for the resource with format projects/{{project}}/global/backendBuckets/{{backend_bucket}}
	ID *string `json:"id,omitempty"`

	// Name Name of the signed URL key.
	Name *string `json:"name,omitempty"`

	// Project The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty"`
}

// BackendBucketSignedURLKeyStatusConditionsItem A Condition that may apply to a resource.
type BackendBucketSignedURLKeyStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BackendBucketSignedURLKeyStatus BackendBucketSignedURLKeyStatus defines the observed state of BackendBucketSignedURLKey.
type BackendBucketSignedURLKeyStatus struct {
	AtProvider *BackendBucketSignedURLKeyStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BackendBucketSignedURLKeyStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BackendBucketSignedURLKey BackendBucketSignedURLKey is the Schema for the BackendBucketSignedURLKeys API. A key for signing Cloud CDN signed URLs for BackendBuckets.
type BackendBucketSignedURLKey struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BackendBucketSignedURLKeyAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BackendBucketSignedURLKeyKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BackendBucketSignedURLKeySpec defines the desired state of BackendBucketSignedURLKey
	Spec *BackendBucketSignedURLKeySpec `json:"spec,omitempty"`

	// Status BackendBucketSignedURLKeyStatus defines the observed state of BackendBucketSignedURLKey.
	Status *BackendBucketSignedURLKeyStatus `json:"status,omitempty"`
}

// IoUpboundGcpComputeV1Beta1BackendBucketSignedURLKeyList BackendBucketSignedURLKeyList is a list of BackendBucketSignedURLKey
type IoUpboundGcpComputeV1Beta1BackendBucketSignedURLKeyList = BackendBucketSignedURLKeyList

// BackendBucketSignedURLKeyList BackendBucketSignedURLKeyList is a list of BackendBucketSignedURLKey
type BackendBucketSignedURLKeyList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of backendbucketsignedurlkeys. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundGcpComputeV1Beta1BackendBucketSignedURLKey `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
